### ISSUE TITLE
Phrase: Turn on/off VPN connection

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdGuardVPNForiOS#120]
In English, you can divide Turn on/off into Turn something on or Turn something off.
But single "Turn" and "Turn on/off" are different meanings in other languages, ex: Chinese.
This makes trouble for translators.
ex: 
https://crowdin.com/translate/adguard-applications/18246/en-zhcn#3944130
Your Chinese Simplified moderator, Dasha, needed to modify "turn" to "connection" in her translation.

https://crowdin.com/translate/adguard-applications/18246/en-zhcn#3944146
English: ${operation}VPN connection ${state}
Dasha's translation: ${state} VPN ${operation}
She ignored "connection" because ${operation} = connection in her translation.
(She also modified ${state} [adj.] = turn on/off [verb] in her other translations.)

It's better to simply modify your program codes to the forms below:
"Turn on" VPN connection
"Turn off" VPN connection
Don't split them.

You can also see your Slovenian moderator's comments for the request on Crowdin.

https://crowdin.com/translate/adguard-applications/18246/en-zhtw#3944130
Turn

https://crowdin.com/translate/adguard-applications/18246/en-zhtw#3944132
${operation}VPN connection

https://crowdin.com/translate/adguard-applications/18246/en-zhtw#3944146
${operation}VPN connection ${state}

https://crowdin.com/translate/adguard-applications/18246/en-zhtw#3944154
Off

https://crowdin.com/translate/adguard-applications/18246/en-zhtw#3944144
On

**Comment by AleksandrShulgin** [comment]
@lancelot-moon Hi
Sorry for the late reply! Unfortunately we cannot to change this structure.
Also we can't divide {operation} and {state}.
And the {state} argument should always be at the end.
