### ISSUE TITLE
Send a push notification when VPN tunnel is stopped/started

### ISSUE THREAD

**Issue by dnovitskyi** [AdguardTeam/AdGuardVPNForiOS#125]
### Problem Description

Customers have no idea when VPN tunnel stops, whether due to the app issues or for any other reasons.

### Proposed Solution

Send a push notification when that happens.

### Alternatives Considered

No viable alternatives.

**Comment by DicerX** [comment]
Must have, VPN disconnects and stays disconnected all the time now.

**Comment by AleksandrShulgin** [comment]
@dnovitskyi  Hi
Thanks for the feature request. It's sounds like a good idea. We'll try to implement it.

**Comment by DicerX** [comment]
Issue is still relevant case should stay open.
