### ISSUE TITLE
Mistaken VPN status in app

### ISSUE THREAD

**Issue by n00d1e5** [AdguardTeam/AdGuardVPNForiOS#143]
### Issue Details

- **AdGuard VPN version:**
1.1.6(293)
- **VPN mode:**
Operating mode: General
- **Device:**
iPhone 12 Pro
- **Operating system and version:**
iOS 15.2.1
### Expected Behavior

The mistaken status happens with the following setting:
- Create an automation (e.g. When device joins some WiFi - Turn AdGuard VPN on)
- Triger the automation
- AdGuard VPN should be now turned on now

### Actual Behavior

Once the automation is triggered, the action of AdGuard VPN switch works properly. The device has a connection thought AdGuard VPN, there is the VPN logo in status bar and VPN on in system setting. However, if I open the AdGuard VPN app, it shows disconnected status.
It means that if I wanna turn off the VPN connection, I have to turn on it first in the app (which is an useless step), then turn it off.

### Screenshots

<details><summary>Screenshot:</summary>

None

</details>

### Additional Information

I also have the TestFlight version. Since it does not give me any additional data volume, I did not install it for several days.
If you want, I can install that so as to provide you the log with TestFlight version. But it seems that they are the same version.

**Comment by zzebrum** [comment]
@n00d1e5 it's working ok on my side, I'm on iOS 15.3.

Why don't you use Wi-fi auto-protection feature in AdGuard VPN instead?
