### ISSUE TITLE
Etsy.com is blocked by VPN

### ISSUE THREAD

**Issue by AleksandrShulgin** [AdguardTeam/AdGuardVPNForiOS#144]
### STR

1. Go to AdGuard VPN and connect to any endpoint
2. Open Safari and go to etsy.com

### Expected Behavior

The website is loaded successfully

### Actual Behavior

The website is blocked

**Comment by gpodder770** [comment]
![IMG_7852](https://github.com/AdguardTeam/AdGuardVPNForiOS/assets/71787759/45938630-783b-4161-9d0e-13e18e1e1c9d)

connecting with usa atlanta location seems to be working now
