### ISSUE TITLE
Системные DNS вместо нефильтрующих по-умолчанию

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardVPNForiOS#146]
Здравствуйте,

насколько я понимаю, сейчас по умолчанию используются нефильтрующие DNS вместо системных от провайдера. При этом они же идут ниже в списке ещё раз🤨Возможно ли добавить опцию использования именно системных DNS от провайдера с той целью, чтобы можно было использовать нативное шифрование ОС при помощи пользовательских .mobileconfig?

Спасибо😏
С уважением.

**Comment by ammnt** [comment]
@ameshkov, есть ли смысл надеяться и верить?😁

**Comment by ameshkov** [comment]
> Возможно ли добавить опцию использования именно системных DNS от провайдера с той целью, чтобы можно было использовать нативное шифрование ОС при помощи пользовательских .mobileconfig?

Тут такая проблема, нативное шифрование **все равно** работать не будет, в iOS оно просто отрубается автоматически когда включен VPN. Так что надо ждать пока мы добавим шифрованные апстримы в сам VPN (скоро добавим)

**Comment by ameshkov** [comment]
Ну и честно говоря провайдерские DNS использовать для VPN-сервиса затея прям скажем так себе:)

**Comment by ameshkov** [comment]
На маке оно честно говоря чудом работает потому что мы там сейчас используем нестандартный механизм поднятия VPN-соединения. Но мы планируем перейти на стандартный механизм как в iOS и там тоже профиль днсный отвалится.
