### ISSUE TITLE
Unable to access to (ALL) Chinese websites via VPN

### ISSUE THREAD

**Issue by n00d1e5** [AdguardTeam/AdGuardVPNForiOS#147]
### Issue Details

- **AdGuard VPN version:**
1.1.6 (293) for iOS & 1.1.0.167 release for macOS
- **VPN mode:**
General mode on iOS & Regular mode on macOS
- **Device:**
iPhone 12 Pro & MacBook Pro (14-inch, 2021)
- **Operating system and version:**
iOS 15.4 & macOS 12.3

### Expected Behavior

The site should be load as always.

### Actual Behavior

Recently, some websites are unaccessible via your VPN, I realized that all unaccessible sites have Chinese IPs. Here are several examples: [sspai 119.23.141.248](https://sspai.com/), [Ali DNS](https://alidns.com), [AliCloud 47.92.40.45](https://www.aliyundrive.com), [Baidu 220.181.38.148](https://baidu.com), [BetaHub 114.80.187.12](https://betahub.cn), [Thunder 39.104.2.218](https://xunlei.com), etc. (Checked with [IP Location](https://www.iplocation.net))
I can confirm that these site are not blocked by local law, at least in Europe, I tested physically in several countries (France, German, Sweden, Netherland, etc.), I can directly access them without any problem. However, I am unable to load them with your VPN connected.

### Additional Information

I tried all versions on iOS and macOS available since February, including released version and testing version, I still have the issue with all versions.
I tried to change DNS server from AdGuard to Google, AliDNS, Blah Dns, nothing works.
The unaccessible website lists is somehow growing rapidly (due to cache updates?), and the issue comes from your servers (and/or setting in the backend).
Please fix it asap, that really impacts for my daily life, I now can not surf with your VPN, which means I paid for nothing...

**Comment by n00d1e5** [comment]
Now, none of your servers works for my daily access website.
I updated to 1.2.0.184 release, and here is the log, even with the option "Record everything", it seems there is no trackroute for my attempt of website access.

```
2022-03-22T08:16:00+0100 (VPNApp/UTUNClient.swift.init(callback:)(43)) debug: TUNNEL	[49] upstream_handler(): Server closed connection 2
2022-03-22T08:16:00+0100 (VPNApp/UTUNClient.swift.init(callback:)(43)) debug: TUNNEL	[49] [L:12-R:2] destroy_connection(): Destroyed
2022-03-22T08:16:00+0100 (VPNApp/UTUNClient.swift.init(callback:)(43)) debug: TUNNEL	[49] destroy_connection(): Remaining connections: client-side=0 server-side=2
2022-03-22T08:16:00+0100 (VPNApp/UTUNClient.swift.init(callback:)(43)) debug: DIRECT_UPSTREAM	[49] [R:31] close_connection(): Closing
```

And here is the traceroute without VPN:

```
traceroute to sspai.com (119.23.141.248), 64 hops max, 52 byte packets
 1  10.121.0.254 (10.121.0.254)  42.944 ms  6.419 ms  2.842 ms
 2  10.1.254.6 (10.1.254.6)  3.463 ms  3.286 ms  3.272 ms
 3  158.64.24.11 (158.64.24.11)  3.712 ms  3.316 ms  3.437 ms
 4  ar-1-lo2.bce.restena.lu (158.64.16.73)  6.095 ms  3.582 ms  3.362 ms
 5  ar-1-lo2.luco.restena.lu (158.64.16.72)  3.242 ms  3.623 ms  3.384 ms
 6  restena-ias-geant-gw.mx1.fra.de.geant.net (83.97.88.137)  7.687 ms  7.874 ms  7.637 ms
 7  ancotel.gm-ff-frk-f-2.163.chinatelecomeurope.com (80.81.195.33)  13.771 ms  10.317 ms *
 8  202.97.89.109 (202.97.89.109)  217.627 ms *  214.996 ms
...
```

And this is the traceroute with your VPN. It is not at all normal...

```
traceroute to sspai.com (119.23.141.248), 64 hops max, 52 byte packets
 1  * * *
 2  * * *
 3  * * *
 4  * * *
 5  * * *
 6  * * *
 7  * * *
 8  * * *
```

```
--- sspai.com ping statistics ---
10 packets transmitted, 0 packets received, 100.0% packet loss
```

**Comment by ameshkov** [comment]
Could you please tell me which AdGuard VPN locations have you tried?

**Comment by n00d1e5** [comment]
> Could you please tell me which AdGuard VPN locations have you tried?

All of them, including the two in China (Hongkong & Taiwan).

**Comment by ameshkov** [comment]
Yeah, it seems they blocked even more endpoints now.

The thing is that for the users inside China the app can check which endpoints are accessible and can be used, but for the users outside China there's no clear way to do the check and the supplied endpoints may be blocked in China.

We'll need to think about it.

**Comment by n00d1e5** [comment]
The condition is not as simple as "inside" or "outside" China. Actually, I am outside China in Europe, I can access correctly all mentioned sites. 
Since the issue started, I traveled several countries and I tried to use the same country's VPN server. it resulting that I am unable to access those website via your VPN.
In the meanwhile, I tried other VPNs, they do not have the same problem.

**Comment by ameshkov** [comment]
> The condition is not as simple as "inside" or "outside" China.

What I am talking about is that when the VPN app runs inside China, it can detect which endpoints are available from there and which are not. We could also check it on our side and prioritize endpoints that are not blocked in China. However, we cannot do it for all our users since most of them simply do not need to access to Chinese websites. We need to find some clear criteria that a user needs this access so that we could prioritize endpoints for such users only. For instance, we could rely on the user's language.

> I am outside China in Europe, I can access correctly all mentioned sites.

Residential IPs aren't blocked in China.

> In the meanwhile, I tried other VPNs, they do not have the same problem.

Do not have yet, GFW blocks VPN servers periodically.

**Comment by n00d1e5** [comment]
I am totally agree with you, and I think that I am the exception (sys language not CN, location setting not in CHN, physical location neither, no Chinese SIM card in the phone, but require to access Chinese websites). It looks like I escaped all the factors, LOL.

The only option looks to be to change IPs with "unblocked" one (or somehow use unblocked IPv6 instead of IPv4?)...

**Comment by ameshkov** [comment]
IP is a limited resource:(

> sys language not CN, location setting not in CHN, physical location neither, no Chinese SIM card in the phone, but require to access Chinese websites

Do you have a Chinese keyboard layout?

**Comment by n00d1e5** [comment]
> Do you have a Chinese keyboard layout?

Yes, I do have it.
I do not know there is an API for the keyboard layer, excellent point!

**Comment by maxikuzmin** [comment]
@n00d1e5 please tell me if the question is still actual?

**Comment by maxikuzmin** [comment]
@n00d1e5 ping

**Comment by n00d1e5** [comment]
> @n00d1e5 please tell me if the question is still actual?

I tired with the server in Frankfurt, some of the mentioned websites are still unaccessible (but not all).

**Comment by ameshkov** [comment]
@n00d1e5 we've configured proper monitor to react to this kind of issues.

Please try the following endpoints:
1. NY
2. Atlanta
3. Singapore
4. Russia
5. Madrid

**Comment by ameshkov** [comment]
@n00d1e5 could you please provide some more example websites access to which we should check besides Ali and Baidu?

**Comment by n00d1e5** [comment]
@ameshkov here is a list, all of them are Chinese websites from my bookmark.
https://sspai.com/
https://alidns.com
https://www.aliyundrive.com
https://baidu.com
https://betahub.cn
https://xunlei.com
https://www.smzdm.com
http://whois.chinaz.com
https://mcc.xunliandata.com/mci-reward/index.html?bkv1=#/login
https://e.bocins.com/EbsWeb/newPagesDlYhkbxzzfw.html
https://www.toodaylab.com

**Comment by maxikuzmin** [comment]
@n00d1e5 we came up with a working solution, we need some time to finalize and test it.

**Comment by maxikuzmin** [comment]
@n00d1e5 question is still relevant?

**Comment by maxikuzmin** [comment]
@n00d1e5 ping

**Comment by n00d1e5** [comment]
> @n00d1e5 question is still relevant?

If I well understood, there is not only me who has the issue. At least, not only me who can reproduce this issue.
I am really like your products, as you said 25 days ago, you camp up with a solution, however, it seems that the solution is not implemented yet.
Because you any one can test if it works with the website listed above.

**Comment by maxikuzmin** [comment]
@n00d1e5 we're going to try something this week and hope it helps.

**Comment by maxikuzmin** [comment]
@n00d1e5 we are testing different options, now Milan and Paris should be available. If everything is okay, we will scale everything.
Please try it and let me know the result.
