### ISSUE TITLE
Auto switch to fastest server

### ISSUE THREAD

**Issue by MoienBowen** [AdguardTeam/AdGuardVPNForiOS#148]
### Problem Description

Recently, I travel a lot. However, the VPN always connects to the chosen server. When I am in France, I choose the French or German server. However, when I travel to Sweden, the speed and ping are significantly decreased, I have to switch to another server manually. 

### Proposed Solution

If the current chosen server is xx% slower than the top1, then switch to the fastest server automatically.

**Comment by MohElbarbary** [comment]
I m really want this option
