### ISSUE TITLE
iOS app kill switch

### ISSUE THREAD

**Issue by mjeshurun** [AdguardTeam/AdGuardVPNForiOS#161]
Hello friends, 
Are there plans to add a kill switch to AdGuard VPN for iOS?

**Comment by maxikuzmin** [comment]
@mjeshurun  for some reason we cannot add this feature at this time.
As soon as it becomes possible, we will definitely add the kill switch to iOS

**Comment by rakleed** [comment]
ProtonVPN also has this feature.

@maxikuzmin @artemiv4nov @Versty do you have any news? And why can't you implement Kill Switch? Because you use your own protocol?
