### ISSUE TITLE
How much data is left/used

### ISSUE THREAD

**Issue by worldsdream** [AdguardTeam/AdGuardVPNForiOS#163]
In the iOS app it shows 4GB for this months traffic. But how do know how much we spend and how much is left?

It would be nice to see how much data is left and used.

For example:
1.2GB/4GB

This means that 1.2GB is left from the total of 4GB

**Comment by maxikuzmin** [comment]
@worldsdream at the moment we display the remaining traffic and an indicator that changes color depending on the remaining traffic. There are no plans to add information about the original traffic yet, maybe we will implement this in the future
