### ISSUE TITLE
IPsec (integrated mode) doesn’t work

### ISSUE THREAD

**Issue by SNH9749** [AdguardTeam/AdGuardVPNForiOS#164]
### Issue Details

- **AdGuard VPN version:**
  - 2.0.3 (7)
- **VPN mode:**
  - integrated
- **Device:**
  - iPhone 13 mini and iPad Pro 2020
- **Operating system and version:**
  - iOS 15.5

### Expected Behavior

Integrated mode should connect.

### Actual Behavior

Integrated mode doesn’t connect at all to any server. Instead, I get an endless connecting message. This is even after reinstalling the app, restarting the device and deleting all VPN profiles.

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information

I’m on iOS 15.5, but I observed this issue since at least iOS 14 - I set AG Blocker to AG implementation and the VPN to Integrated Mode and all I get is the VPN status “Connecting…” endlessly.

I can only use the Blocker and VPN app together by using Native DNS for the Blocker app, and VPN set to use AG’s own protocol.

- I tried to remove all VPN profiles and have them recreated, to no avail.
- I restarted my device several times after each change, nothing.
- Both AG apps are fully up-to-date, only iOS may not be, but I don’t think this is an iOS related issue as this has been present for a while now.

**Comment by SNH9749** [comment]
What’s an interesting observation is that I tried to run Bitdefender’s VPN with the IPsec configuration as well and it doesn’t work either. That is strange—2 different devices but same iOS version and both can’t run IPsec protocols.

Could there be an iOS issue preventing IPsec configs from running?

**Comment by SNH9749** [comment]
I tried on three different devices now:

- iPhone 12
- iPhone 13 mini
- iPad Pro 2020

All are running iOS 15.5, none of them can run IPsec.

**Comment by SNH9749** [comment]
I talked to Apple Support and they had no knowledge of an issue with iOS 15.5 preventing IPsec protocols from working. They suggested to turn to app vendors.

**Comment by SNH9749** [comment]
Tried resetting network settings, that also didn’t help at all. There’s nothing left to try.

**Comment by mozartinio** [comment]
We need you to sent logs to us so we can figure out where is there a problem @SNH9749

**Comment by SNH9749** [comment]
[AdGuardVPNTunnel_logs.txt](https://github.com/AdguardTeam/AdGuardVPNForiOS/files/8939344/AdGuardVPNTunnel_logs.txt)
[AdGuardVPN_logs.txt](https://github.com/AdguardTeam/AdGuardVPNForiOS/files/8939346/AdGuardVPN_logs.txt)

Please let me know if this will do.

**Comment by SNH9749** [comment]
**Additional logs (redacted for sensitive info):**

User info:
    User is logged in: true
    User name/email: REDACTED
    Pro status: true

Application info:
    Build number: 7
    Application id: AA2D766D-85D2-49F9-9102-31FC7E31C72F
    Vpn protocol: AdGuard protocol
    Exclusions mode: regular mode
    Exclusions number: regular = 1; selective: 0
    Dns server: AdGuard DNS
    OnDemand rules: [
    action = connect
    interfaceTypeMatch = any]

Token info:
    Auth token: REDACTED
    Auth token expiration date: 20. 7. 2022, 13:45:42
    Vpn token: REDACTED
    Vpn token expiration date: 23. 1. 2079, 7:47:45
    License key: REDACTED

Current location info:
    id: ZmlfaGVsc2lua2k=
    countryName: Fínsko
    city: Helsinki
    countryCode: FI
    premium only: false
    ping: 80 ms
    ping bonus: 20 ms
    domain: nil
    ip address: nil

Connection status info:
    connection start date: 20. 6. 2022, 8:06:19
    data received: 21901 bytes
    data sent: 10150 bytes

Wi-Fi exclusions:
    current Wi-Fi network: nil
    Wi-Fi exclusions added: 

AdGuard app tunnel info:
Not started

VPN lib version: 0.9.89

**Comment by SNH9749** [comment]
**Logs while trying to connect to IPsec**

[AdGuardVPN_logs.txt](https://github.com/AdguardTeam/AdGuardVPNForiOS/files/8939419/AdGuardVPN_logs.txt)
[AdGuardVPNTunnel_logs.txt](https://github.com/AdguardTeam/AdGuardVPNForiOS/files/8939421/AdGuardVPNTunnel_logs.txt)

**Comment by mozartinio** [comment]
To troubleshoot this issue, we need to get the app logs.

Here's what we need you to do:
AdGuard logs

1. Open Settings --> General --> Turn **Advanced mode** on --> Advanced settings --> Turn **Debug logs** switch on;
2. Reproduce the issue and remember the exact time when it happened;
3. Disable "DNS Privacy";
4. Open the settings --> Support --> **Export logs**;
4. System popup will be opened --> Choose "Mail" app
5. Enter `apple@adguard.com` as a recipient;
6. Mention this issue number in the subject and add the time the issue was reproduced at.
VPN for iOS

VPN logs


1. Open App settings --> Advanced settings --> Logging level --> **Extended**;
2. Reproduce the issue and remember the exact time when it happened;
3. Open the settings --> Support --> **Export logs**;
4. System popup will be opened --> Choose "Mail" app
5. Enter `apple@adguard.com` as a recipient;
6. Mention this issue number in the subject and add the exact time the issue was reproduced at.

**Comment by SNH9749** [comment]
The logs should be with the AdGuard team now @mozartinio. I hope they’ll be able to get something from them, as it was tough trying to connect to IPsec. I’m not sure something even happened, because the UI didn’t show a connecting / disconnecting status this time. All bugged.

**Comment by mozartinio** [comment]
@SNH9749 So here is a thing.. In close future we will fix it for sure but for now there is next temporary solution for it - 
1. Remove the VPN profile of app from the system settings (in the VPN section). 
2. Go to the app and when you click on the "Connect" button, set the VPN profile again.

**Comment by SNH9749** [comment]
I have tried that @mozartinio, it doesn’t work for me. I’ll wait for the fix. Thanks!

**Comment by mozartinio** [comment]
@SNH9749 Hi! Is it still actual on your device?

**Comment by SNH9749** [comment]
Hi m8 @mozartinio 👋

It appears this was present only during my stay in Uzbekistan. Probably a carrier-controlled limitation. Or perhaps it was resolved in an earlier update, I can't be sure, but in Czechia, for example, this is not the case. Integrated mode works well here.

While in Uzbekistan, only the AG VPN protocol worked, thus I couldn't use AG blocker and VPN side by side.

**Comment by mozartinio** [comment]
@SNH9749 by the way we are glad to know that everything works fine now! If something like this will happen again you can reopen this issue:)
