### ISSUE TITLE
Enabling features connects the VPN without the user telling it to

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardVPNForiOS#166]
### Issue Details

- **AdGuard VPN version:**
  - 2.0.4
- **VPN mode:**
  - Integrated mode
- **Device:**
  - iPhone 13 Pro
- **Operating system and version:**
  - iOS 15.6

### Expected Behavior

When enabling app settings, I would not expect AdGuard VPN to automatically connect itself after enablement without user intervention.

### Actual Behavior

When enabling certain app settings, the app automatically connects the VPN after enablement.

### Additional Information

The following settings when enabled are connecting AdGuard VPN from a disconnected state without user intervention:
1. Switching operating mode between general and integrated mode, and visa versa, and
2. Enabling Wi-Fi Auto Protection.

If I’d not noticed the iOS system tile for the VPN connecting, I wouldn’t have known it was connected. This should not be the case.

### Screen Recordings

https://user-images.githubusercontent.com/95468948/177000440-01562a76-02fa-4205-a7ab-7d434f541d44.MOV

https://user-images.githubusercontent.com/95468948/177000441-e1a4a849-e009-4927-8e2d-9d2b4ddb4295.MOV

**Comment by mozartinio** [comment]
@jslawler 
Thank you! In the next release we will fix it.

**Comment by artemiv4nov** [comment]
We have removed the "Auto-protection" functionality, so the task can be closed.
