### ISSUE TITLE
'This month's traffic' does not reduce

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardVPNForiOS#167]
### Issue Details

- **AdGuard VPN version:**
  - 2.0.4
- **VPN mode:**
  - Normal and integrated
- **Device:**
  - iPhone 13 Pro
- **Operating system and version:**
  - iOS 15.6

### Expected Behavior

When using the internet, I'd expect the counter for 'This month's traffic' to get lower.

### Actual Behavior

The counter for 'This month's traffic' stays the same.

</details>

### Additional Information

Tested by downloading Ubuntu (3.65G) under both modes on a trial account.

This has been witnessed by 2 other users in Telegram over the last month.

**Comment by mozartinio** [comment]
@jslawler Hello! We know about this and on the way to fix it. Thanks you for mention it !

**Comment by artemiv4nov** [comment]
The app's behavior has been replaced, please follow updates
