### ISSUE TITLE
Ability to pin favourite servers to the top

### ISSUE THREAD

**Issue by SNH9749** [AdguardTeam/AdGuardVPNForiOS#171]
### Problem Description

Currently, there's no way to pin a favourite server to the top for easier access. I frequently swap servers because some local apps don't work when they detect me "being in another country".

### Proposed Solution

Add the option to pin favourite servers.

**Comment by mozartinio** [comment]
@SNH9749 Hello!
We already have this feature in our plans and will create it for sure! 
Thank you for such useful suggestion!

**Comment by artemiv4nov** [comment]
Duplicated by #174
