### ISSUE TITLE
General operating mode is working alongside AdGuard Ad Blocker

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardVPNForiOS#186]
![image](https://user-images.githubusercontent.com/95468948/198008540-47fcd1a5-9e0e-4d04-995a-5c8dbb0fb2bb.jpeg)

I have AdGuard VPN running in general operating mode.

According to the above screenshot, this should only work with IPSec, which isn't entirely true. Only DNS protection within the AdGuard app won't work. Maybe the integration between both apps can become more synchronous now that AdGuard VPN accepts setting custom DNS.

In the meantime, it might be worth altering the text to reflect that only DNS protection from AdGuard Ad Blocker won't work. After all, it's only 1/3 of the apps blocking capability.

**Comment by mozartinio** [comment]
@jslawler Hello! 
Pretty interesting suggestion, we will think how to rewrite it better
Thank you!

**Comment by artemiv4nov** [comment]
Texts have been changed, please follow updates
