### ISSUE TITLE
DNS server is getting reset to default after a network change

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardVPNForiOS#187]
### Issue Details

- **AdGuard VPN version:**
  - AdGuard VPN v2.0.7 (24)
- **VPN mode:**
  - General
- **Device:**
  - iPhone 13 Pro
- **Operating system and version:**
  - iOS 16

### Steps to reproduce

1. Configure AdGuard VPN to use a custom DNS server (for instance, sign up for AdGuard DNS on https://adguard-dns.io and use it).
2. Connect to Wi-Fi and enable AdGuard VPN.
3. Open https://adguard.com/test.html, verify that you're using AdGuard DNS.
4. Disable Wi-Fi so that the device switched to Cellular.
5. Refresh https://adguard.com/test.html

### Expected Behavior

You should still use your private AG DNS server.

### Actual Behavior

You're switched to AdGuard DNS Non-Filtering (the default one for AG VPN).

**Comment by jmeeter** [comment]
Having this same issue as well with 2.0.7. In my case however I am trying to connect to a VPS running Adguard Home. The only way I can get connectivity is if I use DNS-over-HTTPs or plain IP. Even tried generating a DNS stamp and still could not connect. It appears like I'm not getting an IPV4 address.

Authorization info:
VPN token: 0fe5f1d4-9b01-47f1-96bc-1332c20bfa27
Expiration time: Jun 17, 2076 at 1:47:31 PM
Expiration time, sec: 1692749364
Auth token: lb_a47CIN_KntXfESvaxAuR4ZnM
Expiration time: Nov 26, 2022 at 7:00:19 PM
Expiration time, sec: 2614932
Username: skarz
License status: Unlimited

Device info:
AppID: 0E7C9D1F-18AB-XXXX-9838-A4857AADFE97
DNS server: TLS
Public IP: Updating...

Current endpoint info:
Status: Connected
ID: dXNfc2VhdHRsZQ==
Country: United States
City: Seattle
Premium only: Yes
Ping: 15 ms
Ping bonus: 0 ms
Domain name: vultr-us-sea-02-vzdxphj8.adguard.io
Connected IPv4: 137.xxx.xxx.70:443
Connected IPv6: Unknown

Connection status info:
Protocol: AdGuard
Connection time: Oct 27, 2022 at 1:37:38 PM
Connection time, sec: -28
Data received: Unknown
Data sent: Unknown
Estimate RTT: Unknown
Estimate packet loss: Unknown
Upstreams protocol: Unknown

**Comment by ameshkov** [comment]
@jmeeter well I am pretty sure the client supports DoT and DoQ properly (tested on both AG DNS and AG Home). Please check that the protocols you were trying to use are reachable (try https://github.com/ameshkov/dnslookup for testing).

This "resetting to default" issue does happen anyway regardless of the protocol that's used.

**Comment by jmeeter** [comment]
> @jmeeter well I am pretty sure the client supports DoT and DoQ properly (tested on both AG DNS and AG Home). Please check that the protocols you were trying to use are reachable (try https://github.com/ameshkov/dnslookup for testing).
> 
> This "resetting to default" issue does happen anyway regardless of the protocol that's used.

Please see my bug here: https://github.com/AdguardTeam/AdGuardHome/issues/5075

```
skarz@skarz-ubuntu:~$ dnslookup google.com tls://waguns.net
dnslookup v. 1.8.0-8187
2022/10/28 16:52:49 [fatal] Cannot make the DNS request: getting connection to tls://waguns.net:853: connecting to waguns.net: all dialers failed: 4 errors: "dial tcp 104.21.91.178:853: i/o timeout", "dial tcp 172.67.177.29:853: i/o timeout", "dial tcp [2606:4700:3031::6815:5bb2]:853: i/o timeout", "dial tcp [2606:4700:3032::ac43:b11d]:853: i/o timeout"
```

```
skarz@skarz-ubuntu:~$ dnslookup google.com https://waguns.net/dns-query
dnslookup v. 1.8.0-8187
dnslookup result:
;; opcode: QUERY, status: NOERROR, id: 25377
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version 0; flags: ; udp: 4096

;; QUESTION SECTION:
;google.com.	IN	 A

;; ANSWER SECTION:
google.com.	10	IN	A	142.251.215.238

```

**Comment by ameshkov** [comment]
II'll reply there, this particular issue is about the server configuration, not a bug.
