### ISSUE TITLE
AG VPN – Unlimited & Fast product name is missing for localization

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdGuardVPNForiOS#208]
`AdGuard VPN – Unlimited & Fast` string missing for localization (Crowdin) on the App Store.

<details><summary>App Store</summary>

![image](https://user-images.githubusercontent.com/35523759/213010878-6c70030b-43d9-4a94-9f29-2ebef2452d4c.png)
</details>

<details><summary>Crowdin</summary>

![image](https://user-images.githubusercontent.com/35523759/213011087-db21b22b-e13c-4e30-a0c2-ea4c15761b2e.png)
</details>

**Comment by Versty** [comment]
@gork7777 We are currently using this string for the store search optimisation, so it is intended to not be available for translation in Crowdin for both iOS and Android applications.
