### ISSUE TITLE
Exclusion list in Selective mode goes offset beyond the header if scroll

### ISSUE THREAD

**Issue by VladisLoveZh** [AdguardTeam/AdGuardVPNForiOS#209]
### Issue Details

1)Set AdGuard VPN in Selective mode>
2)Open exclusions list>
3)Scroll domain list and see the list goes beyond the header 
4) Exclusion list in Selective mode goes offset beyond the header upon scrolling. 

- **AdGuard VPN version:**
  -AdGuard VPN for iOS v2.0.7.56 Build number: 56 VPN lib version: 0.11.79
- **VPN mode:**
  - AdGuard Protocol, Selective mode
- **Device:**
  - Any
- **Operating system and version:**
  - iOS

### Expected Behavior

Exclusion list stays in its grid. Visual consistency. 

### Actual Behavior

 Exclusion list in Selective mode goes offset beyond the header if scroll

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/103937301/213111502-7e8bdd06-64b4-445f-8e0a-9435e0c7e17a.png)

</details>

**Comment by artemiv4nov** [comment]
The issue has been fixed, please follow updates
