### ISSUE TITLE
Facebook App does not load content

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/AdGuardVPNForiOS#21]
In some cases images or even complete posts do not load while being connected to AdGuard VPN (+ DNS). Changing the server does not help. I'm mainly connected with the Netherlands server.

**Comment by ameshkov** [comment]
Could you please try choosing a different DNS server OR a different protocol (see "Integrated protocol" in the settings).

Is there any change?

**Comment by iDjay** [comment]
I have the normal AdGuard DNS service disabled. I'm using VPN's build in AdGuard DNS Service.

**Comment by ameshkov** [comment]
Sure, and I am asking to try different settings in the AG VPN app

**Comment by iDjay** [comment]
Might be a Facebook related issue, I can't recreate it with any dns setting. The issue first appeared 1-2 weeks ago, I'll close the issue for the moment.

**Comment by iDjay** [comment]
Here's a screen recording:
https://we.tl/t-HPUj4NQeZa

DNS is not the problem, I'll test if disabling VPN fixes the issue.

**Comment by ameshkov** [comment]
> disabling DNS within VPN fixed the issue

Weird. The thing is that when DNS is disabled, it just uses AdGuard DNS Non-Filtering configuration.

**Comment by iDjay** [comment]
@ameshkov I can see this in the AdGuard for Mac changelog. Maybe it's the same issue?

**Comment by ameshkov** [comment]
@iDjay no, this is a different issue, for sure:)

**Comment by iDjay** [comment]
Anyone able to recreate it?

**Comment by ameshkov** [comment]
Not me:(

**Comment by iDjay** [comment]
@ameshkov seems to be fixed with 1.0.1.

**Comment by ameshkov** [comment]
Tbh, that's strange :)

**Comment by iDjay** [comment]
I guess we can close it for the moment. Seems to be fixed :)
