### ISSUE TITLE
Allow copying the version number by tapping and holding

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardVPNForiOS#213]
### Issue Details

Typing out the version number for a bug report can be tedious swiping back and forth between apps to jot it all down.

### Proposed solution

I’d like the ability to select and copy the version number by tapping and holding on it which is a similar action in other apps.

It makes bug reporting a little easier not having to type out the versions.

![E27E6E7E-9527-4CC1-9953-1E82EEEA54DE](https://user-images.githubusercontent.com/95468948/216825964-6864bf0e-04cd-49e2-bb3f-df24b8682d74.jpeg)

**Comment by artemiv4nov** [comment]
It has been implemented in the new version, please follow updates
