### ISSUE TITLE
AdGuard VPN reconnects unprompted on iOS 16.4

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardVPNForiOS#218]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.0.8(62)

### Operating mode

General

### Environment

```markdown
- OS:iOS 16.4 (20E5212f)
- Device and storage size: iPhone 13 Pro 128gb
```

### Issue Details

When connected, AdGuard VPN reconnects itself unprompted. It seems to happen within seconds of opening the app, after unlocking the device after 5-10mins.

Prior to raising this ticket, the issue occurred twice.
This is possibly related to #216.

Details of setup are in the extended logs emailed to apple@adgard.com.
Look at 17:33 on 24/02/2023, and about 10mins prior to that for the time of occurrence. Logs were exported at the exact moment it happened the second time.

### Expected Behavior

AdGuard VPN does not reconnect unprompted from a connected state.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

iOS 16.4 release notes: https://developer.apple.com/documentation/ios-ipados-release-notes/ios-ipados-16_4-release-notes

**Comment by Versty** [comment]
@jslawler Does this issue reproduce before 16.4 on the same device?

**Comment by jslawler** [comment]
I can't comment on this, I was connected as a test and I noticed the behaviour whilst testing.

**Comment by Versty** [comment]
@jslawler Got it. Seems like a known behaviour, AdGuard VPN is currently under code refactoring, this issue will be fixed in the new version.

**Comment by jslawler** [comment]
@Versty just so for confirmation on your last request.

I was doing some testing and the issue happened on iOS 16.4.1 when opening the AGVPN app (and device at the same time) to the diagnostic info page, whilst also lagging incredibly during the reconnection.

**Comment by artemiv4nov** [comment]
The issue has been fixed, please follow for updates.
