### ISSUE TITLE
Support Passkeys

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardVPNForiOS#219]
### Proposed solution

_Based on industry standards for account authentication, passkeys are easier to use than passwords and far more secure. Adopt passkeys to give people a simple, secure way to sign in to your apps and websites across platforms — with no passwords required._

[What are Passkeys?](https://developer.apple.com/passkeys/)
[Developer documentation](https://developer.apple.com/documentation/authenticationservices/public-private_key_authentication/supporting_passkeys)

**Comment by artemiv4nov** [comment]
We have our own way to log in into account, so we will add some improvements in future versions.
