### ISSUE TITLE
Can’t ping or trace route whilst connected to AdGuard VPN

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardVPNForiOS#222]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.0.8(62)

### Operating mode

General

### Environment

```markdown
- OS: 16.4
- Device and storage size: iPhone 13 Pro, 128gb
```

### Issue Details

When connected to AdGuard VPN, I am unable to use ping or trace route.

Another user on Telegram has reported [the same](https://t.me/adguard_en/219734) with macOS and Android,

### Expected Behavior

Being able to ping and trace route.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

Logs have been sent to apple@adguard.com.
Due to the new YAML format, I can’t upload videos to this issue, so the video is attached to the email.

**Comment by Versty** [comment]
@jslawler Thank you for the report and logs. 
This behaviour will be improved in the future versions.
