### ISSUE TITLE
Please support to export to .ovpn file.

### ISSUE THREAD

**Issue by Rainsting** [AdguardTeam/AdGuardVPNForiOS#223]
### Issue Details

Could you provide a way to export Adguard VPN as *.ovpn format? 

This would allow some routers that support openvpn to directly support Adguard VPN. 

Please consider it, thank you!

**Comment by Versty** [comment]
@Rainsting Hi! 
We use our own AdGuard protocol, which is not based on the OpenVPN protocol. Therefore we have no possibility to export it as `*.ovpn` format.

**Comment by Versty** [comment]
@Rainsting Hi! 
We use our own AdGuard protocol, which is not based on the OpenVPN protocol. Therefore we have no possibility to export it as `*.ovpn` format.
