### ISSUE TITLE
VPN Blocks iOS Apps

### ISSUE THREAD

**Issue by michaellporter** [AdguardTeam/AdGuardVPNForiOS#226]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.0.9(77)

### Operating mode

Integrated

### Environment

```markdown
- OS: 16.3.1
- Device and storage size: iPhone 13 Pro Max, 250GB
```

### Issue Details

The VPN prevented several of my iOS apps from working correctly when enabled. Apps like Rakuten and OpenTable will not work with the VPN active.

![IMG_804AE0231B3D-1](https://user-images.githubusercontent.com/3820529/227574220-740116bd-02fb-4d70-a901-1573987bbb7e.jpeg)

### Expected Behavior

The apps will not load properly when VPN is enabled.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by michaellporter** [comment]
Hello-

The apps have never worked when using the VPN
On Mar 24, 2023 at 11:04 AM -0500, Diana ***@***.***>, wrote:
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

@michaellporter<https://github.com/michaellporter> Did this applications work correctly with the same settings in the previous version of the VPN application?

**Comment by Versty** [comment]
@michaellporter We have tried to reproduce the issue, but both apps work fine on our side. 
Therefore, we would like to know more details. 
Does the issue reproduce with every location in the VPN list? 
Does the issue occur if AdGuard VPN is running but AdGuard for iOS is disabled?

**Comment by Versty** [comment]
@michaellporter Closed due to no reply. Please reopen if needed.
