### ISSUE TITLE
Connections to 223.6.6.6 and 1.1.1.1 and 8.8.8.8

### ISSUE THREAD

**Issue by CaptainComeback** [AdguardTeam/AdGuardVPNForiOS#227]
Hello I was looking through my logs and I kept seeing IP address’s 223.6.6.6, 1.1.1.1 and 8.8.8.8. At first I thought it was something on my phone trying to avoid getting turned down by Adguard dns but then I realized that it appears that it is Adguard VPN making these connections prior to connecting? Is that what I am seeing? 223.6.6.6 is Alibaba DNS and 1.1.1.1 is Cloudflare with 8.8.8.8 being Google of coarse. I was just curious as to why these connections are made every time I make a search while using the VPN too. Thank you and have a good day.

**Comment by Versty** [comment]
@CaptainComeback According to our [Privacy Policy](https://adguard-vpn.com/en/privacy.html) we do not share or sell any personal data of our users.
Could you specify which dns server you are using in the AdGuard VPN?

**Comment by CaptainComeback** [comment]
Yes I am using adguard and I use my personal adguard dns server.Sent from my iPhoneOn Mar 27, 2023, at 12:02 PM, Diana ***@***.***> wrote:﻿
@CaptainComeback According to our Privacy Policy we do not share or sell any personal data of our users.
Could you specify which dns server you are using in the AdGuard VPN?

**Comment by Versty** [comment]
@CaptainComeback We use these IP addresses from time to time to keep our services available to users even in regions where some restrictions apply.
