### ISSUE TITLE
“Fastest” pings show slower than their counterparts in under “All Locations”

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardVPNForiOS#229]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.0.9(77)

### Operating mode

General

### Environment

```markdown
- OS: iOS 16.4.1
- Device and storage size: iPhone 13 Pro 128gb
```

### Issue Details

When opening the AGVPN app, the “Fastest” location pings appear a lot slower than the same location pings under “All locations”.

This generally takes between 1-10 seconds from a cold start.

### Expected Behavior

I would expect the “Fastest” location and the same counterpart under “All locations” to be mirrored to show at the same time, regardless of whether it is the true fastest location or not.

### Screenshots

<details><summary>Screenshot 1:</summary>

https://user-images.githubusercontent.com/95468948/231005881-538d7e97-16fe-480d-ba99-7d5a3a899b29.mov

</details>

### Additional Information

In the above video, refer to Argentina.

**Comment by Versty** [comment]
@jslawler The application first receives pings for each location in the list, then refreshes the list of fastest locations.
AdGuard VPN for iOS is currently under the code refactoring. We will do our best to provide a superior product, including small improvements.
