### ISSUE TITLE
Bing Does Not Display Results on iOS w/ Adguard VPN On

### ISSUE THREAD

**Issue by jaypatrick** [AdguardTeam/AdGuardVPNForiOS#240]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.0.9 (77)

### Operating mode

Integrated

### Environment

```markdown
- OS: iOS 16.5
- Device and storage size: iPhone 12 Pro Max (128gb)
```

### Issue Details

Any time AdGuard VPN is on in integrated mode with Adguard for iOS, Bing search results do not display. Turning off the VPN (But keeping Adguard running) and Bing works properly. THe search page is completely blank, no HTML at all. This does not happen with Google/etc, only Bing, and it is enough of an issue that I never use the VPN since I do many internet searches daily as part of my job (Software Engineer).

### Expected Behavior

Bing should work properly.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Versty** [comment]
@jaypatrick Hi! 
Does the issue persist if you switch to any other location in AdGuard VPN? 
Please try a couple of different locations and let me know the result

**Comment by Versty** [comment]
@jaypatrick Any updates?

**Comment by Versty** [comment]
@jaypatrick Closed due to lack of activity. 
Please reopen if needed.
