### ISSUE TITLE
Grey background is visible behind the server list popup for some screen sizes

### ISSUE THREAD

**Issue by Versty** [AdguardTeam/AdGuardVPNForiOS#243]
### Version
AdGuard VPN for iOS 2.0.9

### Environment
iPhone XR, 6.1" display

### How to reproduce 
Launch AdGuard VPN

### Expected behaviour 

<p align="left">
<img src="https://github.com/AdguardTeam/AdGuardVPNForiOS/assets/107266340/026240ff-d2ab-4dbb-83af-1cebeffabbe2" width="300" height="650">
</p>

### Actual behaviour

<p align="left">
<img src="https://github.com/AdguardTeam/AdGuardVPNForiOS/assets/107266340/972001f0-1256-4a98-a62a-5b15905f0ba2" width="300" height="650">
</p>

**Comment by artemiv4nov** [comment]
The task has been fixed, follow for official Beta version please.
