### ISSUE TITLE
No stream from camera with HSV

### ISSUE THREAD

**Issue by Fire5Lion** [AdguardTeam/AdGuardVPNForiOS#254]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.0.10 (78)

### Operating mode

General

### Environment

```markdown
- OS: 17
- Device and storage size: iPhone 13 Pro 256GB
```

### Issue Details

The stream from the camera with HomeKit secure video does not work if connected
wifi + adguardvpn. Work on 4g + adguardvpn. Video history and snapshots works. Operating mode - General and Integrated. Quic - on/off. different locations. No problem with other vpn - Proton and StrongVpn

On macOS works

[AdGuardVPN_logs.zip](https://github.com/AdguardTeam/AdGuardVPNForiOS/files/12169655/AdGuardVPN_logs.zip)

### Expected Behavior

Connecting to a Camera with HomeKit Secure Video

### Screenshots

<details><summary>Screenshot 1:</summary>

<
![2BE99452-4F27-4A8D-947B-6983AD1DD8E5_1_102_o](https://github.com/AdguardTeam/AdGuardVPNForiOS/assets/97465379/7d71387c-33bf-4110-b77c-f6715af12943)
>

</details>

**Comment by AleksandrKalininAdGuard** [comment]
CRM #785664 screencast in the ticket.
[AdGuardVPN_logs (20).zip](https://github.com/AdguardTeam/AdGuardVPNForiOS/files/12213106/AdGuardVPN_logs.20.zip)

**Comment by Versty** [comment]
@Fire5Lion Добрый день! 
Мы ознакомились с видео и передали логи с вашего устройства разработчикам на изучение. 

Давайте попробуем изменить DNS сервер, скорее всего это решит проблему. 
В приложении AdGuard VPN откройте вкладку App settings, нажмите на настройку DNS server, выберите из списка AdGuard DNS или Google DNS .

**Comment by Fire5Lion** [comment]
Не работает

![IMG_1181](https://github.com/AdguardTeam/AdGuardVPNForiOS/assets/97465379/d74d9607-e3a4-47a7-9af2-317694b4d0c5)

![IMG_1182](https://github.com/AdguardTeam/AdGuardVPNForiOS/assets/97465379/0cf4088f-c392-4124-b6e5-46ac27e07597)
![IMG_1183](https://github.com/AdguardTeam/AdGuardVPNForiOS/assets/97465379/ca8388e8-090b-47cc-8908-6d4dcc9f3cb2)
[logs 080823.zip](https://github.com/AdguardTeam/AdGuardVPNForiOS/files/12290351/logs.080823.zip)

**Comment by Versty** [comment]
@Fire5Lion Добрый день! 
Мы изучили ваши логи, и для поиска причины нам потребуется более подробная информация. 

1. Пожалуйста, обновите приложение до последней версии 2.1 и включите расширенный уровень логирования (Настройки -> Настройки приложения -> Расширенные настройки -> Уровень логирования -> Расширенный) 

2. Подключитесь к сети, в которой воспроизводится проблема 

3. Подключитесь к серверу в локации в приложении AdGuard VPN и воспроизведите проблему 
   - **Запишите или запомните точное время воспроизведения** 

4. Экспортируйте логи через функцию в приложении (Настройки -> Поддержка -> Экспортировать логи) 
   - Выберите приложение "Почта", в заголовке письма укажите номер `254`
   - В теме письма оставьте информацию о времени воспроизведения 
   - Отправьте письмо с файлом по адресу `apple@adguard.com`

**Comment by Fire5Lion** [comment]
Отправлено

**Comment by Fire5Lion** [comment]
Отказался от использования AdGuard и AdGuard vpn
По комментарию Ваших разрабов, разбираться сейчас с этим никто не будет.
