### ISSUE TITLE
No working in MTS

### ISSUE THREAD

**Issue by psnrk** [AdguardTeam/AdGuardVPNForiOS#255]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.1

### Operating mode

Integrated

### Environment

```markdown
- OS:16.6
- Device and storage size: iphone 14, 128GB
```

### Issue Details

Не работает с мобильным оператором МТС (Новосибирск), не подключается, с Ростелекомом проблем нет, подключается быстро и стабильно. Пару-тройку месяцев назад подключался к МТС без проблем.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by ESurina** [comment]
Здравствуйте! Это, к сожалению, вызвано ограничениями со стороны мобильных операторов. Скорее всего в ближайшее время протокол IPSec не заработает в России, поэтому можем посоветовать вам использовать режим интеграции только при подключении к Wi-Fi или переключить режим на VPN.
