### ISSUE TITLE
2FA autofill does not show on keyboard when logging in with Apple

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardVPNForiOS#258]
![image](https://github.com/AdguardTeam/AdGuardVPNForiOS/assets/95468948/4df9c59d-c3be-4e95-b3d1-d81b2ed4f351)

I assume the same will be for all third party login methods as they're loaded within the in-app browser.

**Comment by ESurina** [comment]
Thank you for bringing this issue to our attention. Unfortunately, we are unable to solve it, as it depends only on the Safari developers.
