### ISSUE TITLE
Abnormally high ping to closest server (Sydney, Australia)

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardVPNForiOS#261]
The same as [this](https://github.com/AdguardTeam/AdGuardVPNForiOS/issues/231) issue.

The closest server to me is the Sydney, Australia. Usually this gives me a ping of around 25ms, it is currently giving me a ping of around 110ms.

Additionally, the VPN keeps reconnecting almost every time I open the app.
A button saying "Nudge" appeared in the app, so I presume it sent you a notification of the issue.

Default logging level logs have been sent to apple@adguard.com, with the issue as the subject title.

![image](https://github.com/AdguardTeam/AdGuardVPNForiOS/assets/95468948/06a03247-a04b-446c-8764-a849897c4a28)

**Comment by ESurina** [comment]
We will try to fix it in the next versions!
