### ISSUE TITLE
Show beta release notes

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardVPNForiOS#267]
Any chance we could start getting the release notes for the AdGuard VPN for iOS beta's added to the website/GH repo/Telegram, etc so that we can actually see something more than just stability fixes, and bug fixes?

**Comment by zzebrum** [comment]
@jslawler Usually, when we have implemented some important features or fixed some important bugs, we specify in the What's New section where we ask for your attention. 

And we use "minor fixes" or "improved stability" in cases where for example we updated VPN libs and really just improved stability, fixed some crashes and so on. And all we need from our beta testers is just to continue using the app in a normal way.
