### ISSUE TITLE
Add ability to copy app version in About in AdGuard VPN

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdGuardVPNForiOS#274]
### Issue Details

In order for the user to send a version number to support or when creating an issue on GitHub, he needs to manually enter the version number, which is not convenient.

### Proposed solution

Add the ability to copy the app version in the About section of the settings.

**Comment by ESurina** [comment]
We will add it in the next versions!

**Comment by artemiv4nov** [comment]
It has been done in the v2.2 version.

**Comment by rakleed** [comment]
@artemiv4nov can you close the issue when this version is publicly available?
