### ISSUE TITLE
Add `Version history` link to About section of settings

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdGuardVPNForiOS#275]
### Issue Details

Now it's hard to find a link to the version history of the app.

### Proposed solution

Add the [Version history](https://adguard-vpn.com/en/versions/ios/release.html) link to the About section of settings.

**Comment by ESurina** [comment]
We will add it in the next version!

**Comment by rakleed** [comment]
@ESurina could you close the issue when this feature will be available in the release version?
