### ISSUE TITLE
Improve name of file with exported list of exclusion sites

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdGuardVPNForiOS#276]
### Issue Details

Currently, when exporting a list of exception sites, the file is called `exclusions`, but I would like it to have a descriptive and uniform name on any device.

### Proposed solution

Name the file with the exported list of exclusion sites like this: `adguard-vpn_ios_website-exclusions_2023-09-04_22-41-27`.

**Comment by artemiv4nov** [comment]
As a said in android repo, it's nice idea, we will append an 'ios' phrase to the name.
