### ISSUE TITLE
In `README`, logo is hard to see when using dark theme in GitHub

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdGuardVPNForiOS#277]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

N/A

### Operating mode

None

### Environment

```markdown
- OS: N/A
- Device and storage size: N/A
```

### Issue Details

In the https://github.com/AdguardTeam/AdGuardVPNForiOS/blob/master/README.md, the logo is hard to see when using the dark theme on GitHub.

### Expected Behavior

You need to add a logo option for the dark theme. I wanted to do it myself by taking [this dark theme logo](https://github.com/AdguardTeam/AdGuardVPNExtension/blob/63d72c1dace95f4a332e2c350ad6b7ddf027a93d/src/assets/images/logo-vpn-dark.svg), but it doesn't have mentions to which platform the repository belongs, which is in the current logo.

Useful links: https://github.blog/changelog/2021-11-24-specify-theme-context-for-images-in-markdown/
https://github.blog/changelog/2022-08-15-specify-theme-context-for-images-in-markdown-ga/

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://github.com/AdguardTeam/AdGuardVPNForiOS/assets/19418601/ae123273-a950-44f1-833c-d8626f75a688)

</details>

**Comment by Versty** [comment]
@rakleed done!
