### ISSUE TITLE
No space between version and build number in `About`

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdGuardVPNForiOS#278]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.1.0 (1305)

### Operating mode

General

### Environment

```markdown
- OS: iOS 16.6
- Device and storage size: iPhone XR, 64 GB
```

### Issue Details

There is no space between version and build number in AdGuard settings in `About` section.

### Expected Behavior

In the AdGuard settings, in the "About" section, there is a space between the version and the build number.

### Screenshots

<details><summary>Screenshot 1:</summary>

![IMG_4349](https://github.com/AdguardTeam/AdGuardVPNForiOS/assets/19418601/3fc9e7d0-ff26-4c22-a23a-e1409ecc6ee8)

</details>

**Comment by Versty** [comment]
@rakleed Hi! 
We continue to work on refactoring the application and have already redesigned the About screen. 
Hope you'll like the new changes when the renewed version becomes available.

**Comment by rakleed** [comment]
@Versty could you close the issue when this feature will be available in the release version?
