### ISSUE TITLE
Can‘t access DAZN

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardVPNForiOS#28]
Similar like the Disney+ issue, I can't access DAZN (sports streaming service) while being connected to the German VPN server. I guess the problem is that my DNS location is elsewhere?!

![image](https://user-images.githubusercontent.com/4127356/99372701-d9edbc00-28c0-11eb-9c84-e8e2c46f4a46.png)

**Comment by iDjay** [comment]
https://github.com/AdguardTeam/AdGuardVPNForiOS/issues/11

**Comment by Ruslanrem** [comment]
@iDjay hi, from which country You are from?

**Comment by iDjay** [comment]
Germany. Dazn Account is german, adguard server is German :)

**Comment by zzebrum** [comment]
@iDjay in general it is not really hard to detect when someone using a VPN. So some apps\websites detect such cases :) 
Right now we are working on it and hope we will fix it.

**Comment by iDjay** [comment]
Any news when this will be fixed?

**Comment by ameshkov** [comment]
Not yet. We'll first address bittorrent, streaming services are planned after that.
