### ISSUE TITLE
Add information about beta in settings

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdGuardVPNForiOS#280]
### Issue Details

Now, in order to try new features and check out fixes in the beta version, the user needs to find information on where and how to install it.

### Proposed solution

Add information about the beta to the settings and a link to how you can install it: https://adguard-vpn.com/en/beta.html?platform=ios

**Comment by artemiv4nov** [comment]
The version info could be found on the "About" screen since v2.2.

**Comment by rakleed** [comment]
@artemiv4nov my suggestion was to add information to the settings about how you can test the beta version. Since now you can only find out about this in the help article on the KB website, but this information is challenging to find.
