### ISSUE TITLE
Not connect in Integrated mode

### ISSUE THREAD

**Issue by Fire5Lion** [AdguardTeam/AdGuardVPNForiOS#282]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.1.0 (1305)

### Operating mode

Integrated

### Environment

```markdown
- OS: 17.0 
- Device and storage size: iPhone 13 Pro 256
```

### Issue Details

Нет подключения к серверам в интегрированном режиме. Adguard при этом может быть отключен. DNS сервер любой.
Провайдер Ростелеком, Билайн

### Screenshots

<details><summary>Screenshot 1:</summary>

![IMG_1204](https://github.com/AdguardTeam/AdGuardVPNForiOS/assets/97465379/9f4f97d9-88f6-43d0-aed7-31ff89d19b41)

</details>

[AdGuardVPN_logs.zip](https://github.com/AdguardTeam/AdGuardVPNForiOS/files/12560013/AdGuardVPN_logs.zip)

**Comment by ESurina** [comment]
При интеграционном режиме используется протокол IPSec, на который имеются ограничения со стороны провайдеров. Мы стараемся поддерживать доступность сервиса. Сейчас вы можете использовать режим VPN, и он будет работать.
