### ISSUE TITLE
Rename `Leave feedback` to `Report a bug` in settings in Support

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdGuardVPNForiOS#287]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.1.0 (1305)

### Operating mode

General

### Environment

```markdown
- OS: iOS 16.6.1
- Device and storage size: iPhone XR, 64 GB
```

### Issue Details

On all other platforms, the `Leave feedback` button simply opens a form for general feedback like https://link.adtidy.net/forward.html?action=feedback&from=menu&app=vpn_mac, which implies sending general feedback, without logs. But when you click “Report a bug” on other platforms, a message is sent directly to support with logs.

### Expected Behavior

In the settings in the Support section, the button for contacting support should be called `Report a bug`.

### Screenshots

<details><summary>Screenshots:</summary>

<img src="https://github.com/AdguardTeam/AdGuardVPNForiOS/assets/19418601/ace65db7-0491-4994-a4c7-e6d1ac9232d0" width="300"> <img src="https://github.com/AdguardTeam/AdGuardVPNForiOS/assets/19418601/4363ba57-db8b-480f-8307-36adb419f2a6" width="300">

</details>

**Comment by ESurina** [comment]
We will change it in the next versions!

**Comment by rakleed** [comment]
@ESurina could you close the issue when this feature will be available in the release version?
