### ISSUE TITLE
Add server in Argentina

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/AdGuardVPNForiOS#29]

**Comment by Ruslanrem** [comment]
@iDjay  we will expand the geography of our servers, in the nearest future they will appear in Argentina also

**Comment by iDjay** [comment]
@Ruslanrem any news? :)

**Comment by iDjay** [comment]
Any updates? :)

**Comment by denis9229** [comment]
Hello
Yes, we plan to increase the number of locations in South America. We will try to add as soon as possible =)

**Comment by iDjay** [comment]
any news here @denis9229 ? :)

**Comment by denis9229** [comment]
> any news here @denis9229 ? :)

Not yet, but I think that soon we will expand the number of locations and try to add Argentina
