### ISSUE TITLE
AdGuard not working 

### ISSUE THREAD

**Issue by Amir-Osman0v** [AdguardTeam/AdGuardVPNForiOS#293]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.1.1

### Operating mode

None

### Environment

```markdown
- OS:16.6.1
- Device and storage size:iPhone Xs
```

### Issue Details

As usual, I wanted to connect to the region (Finland) through Adguard, the VPN connected, but did not download anything, and on the second day it generally began to write that most regions were not online.

### Expected Behavior

I will turn on the VPN and it will work again

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

![IMG_4160](https://github.com/AdguardTeam/AdGuardVPNForiOS/assets/145204427/468961cd-d3f1-429a-9522-32172e02d651)

**Comment by Versty** [comment]
@Amir-Osman0v Добый день! 
Проблема связана с тем, что на территории РФ начали массово блокировать VPN-сервисы. 
Периодически возможны перебои в работе, потому что блокировки все время меняют свои специфику и направленность. Мы делаем все возможное, чтобы поддерживать работоспособность сервиса даже в сетях с ограничениями.
