### ISSUE TITLE
Bug with access while using VPN

### ISSUE THREAD

**Issue by OksanaBuntova** [AdguardTeam/AdGuardVPNForiOS#295]
### Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.0.10(78)

### Operating mode

General

### Environment

```markdown
- OS:IOS (16.2)
- Device and storage size:iPhone 14, 128 gb
```

### Issue Details

Hello! 
my account (login rvyhy94vmm@privaterelay.appleid.com) has a license (duration date 30.07.2024). I can activate VPN in application, but is doesn’t work, for example, I can’t use instagram and the same app with this VPN. I tried to change the country, but the result was the same. 
this problem period starts in 2 September. Before this time vpn has worked correctly. 

### Expected Behavior

Please, normalize work of vpn for my account. 

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

-

**Comment by ESurina** [comment]
Please try to update the application to version 2.1.1. It is available in the App Store.
