### ISSUE TITLE
Verification code autofill and iOS 17 autofill not working when logging in with Apple account

### ISSUE THREAD

**Issue by kyjhoz-mikfip-goXci0** [AdguardTeam/AdGuardVPNForiOS#301]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.1.4

### Operating mode

General

### Environment

```markdown
- OS: iOS 17.2
- Device and storage size: iPhone 13 Pro
```

### Issue Details

When selecting the login with Apple method, it opens up a browser window internal to the app to login using your Apple ID.

Upon verifying the Apple ID, you’re then redirected to AdGuard’s 2FA login page.

In all other AdGuard products I’ve used on iOS, I would be able to enter the verification code saved on iOS passwords automatically from the QuickType bar by selecting it.

If this fails to work, as of iOS 17, by holding the text box, an autofill popup can also be used. In AdGuard’s verification code page however, it is not recognised as a page to enter password information, it registers as a contact page instead, which then forces me to navigate to iOS settings to manually fetch the 2FA password instead.

### Expected Behavior

Both being able to automatically enter the verification code using the QuickType bar button or using the autofill popup feature when holding the verification code text box.

### Screenshots

<details><summary>Screenshot 1:</summary>

https://github.com/AdguardTeam/AdGuardVPNForiOS/assets/149243371/5d9c6d54-161f-4ae3-b766-5c9aac5d373c

</details>

### Additional Information

https://developer.apple.com/documentation/security/password_autofill/about_the_password_autofill_workflow

**Comment by maxikuzmin** [comment]
@kyjhoz-mikfip-goXci0 thanks! We will solve this problem in the near future

**Comment by maxikuzmin** [comment]
@kyjhoz-mikfip-goXci0 this issue is being moved to another repository. We will fix autofill in the next updates
