### ISSUE TITLE
AdGuard VPN for iOS not working

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardVPNForiOS#312]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.1.4

### Operating mode

Integrated

### Environment

```markdown
- OS: iPad OS 17
- Device and storage size: iPad 6th generation 32GB of Storage.
```

### Issue Details

I am not able to connect to any VPN server. Also, I get a message saying, “The VPN could have been blocked in your country, or there is a glitch.” 

### Expected Behavior

You should be able to connect to the VPN and show the server names in the application. 

### Screenshots

![IMG_0019](https://github.com/AdguardTeam/AdGuardVPNForiOS/assets/96619913/b4e613ff-e947-48d7-a1f2-9e08de35b80e)

### Additional Information

This issue is also happening on AdGuard VPN for Windows, where I cannot use the VPN at all.

**Comment by ESurina** [comment]
The integration mode uses the IPSec protocol, which in some countries now has restrictions from providers. We do our best to maintain service availability. For now, we recommend using AdGuard VPN in VPN mode.
