### ISSUE TITLE
VPN reconnects when switching apps

### ISSUE THREAD

**Issue by kyjhoz-mikfip-goXci0** [AdguardTeam/AdGuardVPNForiOS#328]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.1.4

### Operating mode

General

### Environment

```markdown
- OS:iOS 17.3
- Device and storage size: iPhone 13 Pro 128gb
```

### Issue Details

When using the app switcher, the VPN reproducably reconnects every time I switch to/from the AdGuard VPN app, or other apps.

### Expected Behavior

AdGuard vpn does not reconnect.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

Logs set to Apple@adguard.com.

**Comment by Versty** [comment]
@kyjhoz-mikfip-goXci0 AdGuard VPN for iOS 2.2 is a completely reworked version of the app. The new version should fix such issues, so use the RC version 2.2 as a temporary solution and wait for the official release.
