### ISSUE TITLE
Good

### ISSUE THREAD

**Issue by Blincwear88** [AdguardTeam/AdGuardVPNForiOS#331]
Good

_Originally posted by @Maxzybx in https://github.com/Uniswap/tokenlists-org/issues/2629#issuecomment-1925357174_

_Originally posted by @Maxzybx in https://github.com/trustwallet/assets/issues/27339_

_Originally posted by @Maxzybx in https://github.com/Maxzybx/Maxwell/issues/1_

**Comment by Blincwear88** [comment]
`
[GitHub Invoiced Sponsor Agreement-2024-02-02.pdf](https://github.com/AdguardTeam/AdGuardVPNForiOS/files/14175058/GitHub.Invoiced.Sponsor.Agreement-2024-02-02.pdf)
`

**Comment by Maxzybx** [comment]
Hi
