### ISSUE TITLE
Prevent Smart Punctuation from altering DNS server addresses

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardVPNForiOS#357]
### Issue Details

When using a DNS server address with double hyphens, iOS’s Smart Punctuation feature turns the double hyphens into an emdash, which alters the server address, resulting in no connection.

Currently the only workaround is to copy and paste a server address in. Manually typing it won’t work.

![image](https://github.com/AdguardTeam/AdGuardVPNForiOS/assets/149243371/02969681-ef55-4d49-baa6-89ec90ffb4d5)

![image](https://github.com/AdguardTeam/AdGuardVPNForiOS/assets/149243371/ce526105-3221-4a4a-8be6-cc30070b332b)

### Proposed solution

Programmatically prevent iOS Smart Punctuation from altering text when entering in DNS servers.

Something like the following in Swift may be a solution:

```
if #available(iOS 11.0, *) {
    textView.smartDashesType = .no
    textView.smartQuotesType = .no
    textView.smartInsertDeleteType = .no
} else {
    // Fallback on earlier versions
}
```

**Comment by Natthaphonkanchaisri** [comment]
Natthaphon99.com
