### ISSUE TITLE
Log technical and interaction data sent

### ISSUE THREAD

**Issue by jslawler-gh** [AdguardTeam/AdGuardVPNForiOS#358]
### Issue Details

When enabling “Send technical and interaction data”, it would be nice to know what exactly has been sent other than the broad spectrum of information listed in the privacy policy.

### Proposed solution

Log the data sent accessible to the user.

**Comment by PavelParkhomenko** [comment]
Hello! Just to clarify, are you referring to something similar to a 'History' feature where the information sent to us, along with dates, is listed?

**Comment by PavelParkhomenko** [comment]
Thank you for clarifying! Regrettably, at present, it's not feasible to enable logging for all these events. However, please be informed that we will soon update our Legal documents section on our webpage[ https://adguard-vpn.com/](https://adguard-vpn.com/). This update will provide more comprehensive details regarding the data we collect and process.
