### ISSUE TITLE
When Connected to Canadian Servers in Adguard VPN for iOS I can't get canadian Prime Video

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardVPNForiOS#374]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN  version

AdGuard VPN v2.4 Beta 1 & v2.3.1 Release

### Environment

- OS: 17.5.1
- Device: iPad, iphone

### Operating mode

Integrated

### Exclusions mode

None, AdGuard VPN app works in integrated mode

### Which DNS server do you use?

None, AdGuard VPN app works in integrated mode

### Custom DNS

AdGuard Private DNS

### Issue Details

Steps to reproduce:
1. Put AdGuard VPN for iOS on all Canadian servers (of which there are only 2)
2. Open Prime Video and click on the title 
3. It doesn't say Play

### Expected Behavior

You should be able to play Canadian Prime Video with AdGuard VPN for iOS enabled on Canadian VPN Servers.

### Actual Behavior

I get a message when clicking on the titles, and the message reads, "Your device is connected to the Internet using a VPN or Proxy service. Please disable it and try again. For more help, go to primevideo.com/vpn"

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

### Additional Information

It happens with AdGuard VPN for Android with Prime Video when on Canadian Servers, so you also know.

**Comment by Versty** [comment]
@Batman2814 Hi! 

Amazon Prime is available exclusively on USA and Japan locations. 
Please use this servers to watch Amazon Prime videos.
