### ISSUE TITLE
Missing country flags for new servers

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdGuardVPNForiOS#381]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN  version

2.3.2

### Environment

- OS: iOS 17.6.1
- Device: iPhone 15 Pro

### Operating mode

VPN

### Exclusions mode

Selective

### Which DNS server do you use?

Cloudflare DNS

### Issue Details

Steps to reproduce:
1. Open list of locations

### Expected Behavior

The country flag will be displayed for all locations.

### Actual Behavior

Country flag is not displayed for new locations (China, Iceland, Iran, Latvia, Lithuania, Moldova).

### Screenshots

<details><summary>Screenshots</summary>

![IMG_5816](https://github.com/user-attachments/assets/4dc5a18c-00a0-4c80-9f53-bdba296f9ad3)

![IMG_5817](https://github.com/user-attachments/assets/0be6c21b-c5f5-495a-b41b-0f5e10d2c5b3)

![IMG_5818](https://github.com/user-attachments/assets/fb3a03d8-7037-4754-bd12-ba1a63a42011)

</details>

**Comment by ESurina** [comment]
Thank you for bringing this issue to our attention! We've already fixed it. The change will be included in version 2.4.
