### ISSUE TITLE
Can’t add `x.com` to exclusion list

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdGuardVPNForiOS#382]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN  version

2.3.2

### Environment

- OS: 17.6.1
- Device: iPhone 15 Pro

### Operating mode

VPN

### Exclusions mode

Selective

### Which DNS server do you use?

Custom DNS

### Custom DNS

Private AdGuard DNS

### Issue Details

Steps to reproduce:
1. Open `Exclusions` tab
2. Click `+ Add website`
3. Enter `x.com`
4. Click `Save`

### Expected Behavior

New domain was added.

### Actual Behavior

I get an error message `Invalid value`.

### Screenshots

<details><summary>Screenshot 1</summary>

![IMG_5886](https://github.com/user-attachments/assets/1477e2bc-6f79-4457-a6a6-4e2bb4e35102)

</details>

**Comment by Versty** [comment]
@rakleed Will be fixed soon. 
Please take a look at the #347 issue.
