### ISSUE TITLE
Support iOS 18 dark and tinted icons

### ISSUE THREAD

**Issue by emeritaacuity0u** [AdguardTeam/AdGuardVPNForiOS#392]
### Issue Details

iOS 18 allows for apps to now have dark and tinted icons which AdGuard does not yet support.

### Proposed solution

Add dark and tinted icon support.
https://developer.apple.com/design/human-interface-guidelines/app-icons

**Comment by Versty** [comment]
@emeritaacuity0u HI! 
Why did you close this issue?

**Comment by emeritaacuity0u** [comment]
Duplicate of #387
