### ISSUE TITLE
Add banking websites to exception rules

### ISSUE THREAD

**Issue by minternational** [AdguardTeam/AdGuardVPNForiOS#394]
### Issue Details

I like the predefined exception rules but I can't find banking websites.

### Proposed solution

Add banking websites like ING, DKB, Trade Republic and so on.
Thank you :)

**Comment by ESurina** [comment]
Do you mean this list of websites?
![IMG_0301](https://github.com/user-attachments/assets/5f661638-2502-47c2-a613-2d4d24f30149)

**Comment by minternational** [comment]
Yes :)

**Comment by ESurina** [comment]
Great idea! Maybe we’ll add it in the future, but for now it’s suggested that you manually enter exclusions.
