### ISSUE TITLE
I can't update the app according to your instructions (new Apple ID account created)

### ISSUE THREAD

**Issue by Oliverdeus-cloud** [AdguardTeam/AdGuardVPNForiOS#395]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN  version

2.3.2

### Environment

- OS: 17.7
- Device: iPhone XS

### Operating mode

VPN

### Exclusions mode

None, AdGuard VPN app works in integrated mode

### Which DNS server do you use?

None, AdGuard VPN app works in integrated mode

### Issue Details

Steps to reproduce:
1. I created a new Apple ID account according to your instructions to update your applications to the current version.
2. The App Store gives an error, the screenshot I took is attached to this request
3. Please tell me if it makes sense to delete the app and download it again using a new Apple ID (with the United States of America region)? I would not like to lose the app, so I did not delete it, but decided to ask you. Thank you.

### Expected Behavior

I expected that after creating a new Apple ID according to your instructions on the site I would be able to update your application to the current version without any problems, but this did not happen

### Actual Behavior

Instead of the expected result, the App Store reports that the application is no longer available (the developer has removed this application from the App Store).
![IMG_0249](https://github.com/user-attachments/assets/f93b7cfd-3d54-4500-9016-b1919fb035fe)

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by Versty** [comment]
@Oliverdeus-cloud Hi! 
First, make sure that the App Store region is the United States and that app prices are displayed in US dollars. 
Then, if the prices are still in rubles, follow the instructions on how to change the region on https://change-appstore-country.com/ru website.

**Comment by Oliverdeus-cloud** [comment]
Only after I uninstalled the application, I was able to download and install it on Device. Failed to update. Nevertheless, thank you very much!
