### ISSUE TITLE
Preferred IPv6 Version Issue Causing AdGuard VPN to Fail on iOS

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardVPNForiOS#396]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN  version

2.4

### Environment

- OS: 18.0.1
- Device: 13 Pro

### Operating mode

VPN

### Exclusions mode

None, AdGuard VPN app works in integrated mode

### Which DNS server do you use?

AdGuard DNS

### Custom DNS

AdGuard personal DNS (h3)

### Issue Details

Steps to reproduce:
1. Set preferred IP version to IPv6

### Expected Behavior

VPN reconnects, using IPv6

### Actual Behavior

VPN hangs on connecting….

### Screenshots

<details><summary>Screenshot 1</summary>

![IMG_0040](https://github.com/user-attachments/assets/a3b7c7e3-3e49-4572-bb3a-0cb26d190104)

![IMG_0039](https://github.com/user-attachments/assets/baf93f13-4b60-405e-8739-adec5d07ed6c)

</details>

**Comment by maxikuzmin** [comment]
@emeritaacuity0u does your WiFi network support IPv6?

**Comment by emeritaacuity0u** [comment]
Yes, natively, both the ISP and my network supports IPv6.

**Comment by emeritaacuity0u** [comment]
> @emeritaacuity0u could you please clarify if ipv6.google.com opens in your browser?

It does.

![image](https://github.com/user-attachments/assets/18686ed2-4d53-4955-b7be-e0f545cd1bb6)

**Comment by maxikuzmin** [comment]
@emeritaacuity0u In order to troubleshoot this issue, we need to get your application logs.

Here's what we need you to do:

1. Enable debug logging:
*Settings -> General -> Advanced -> Logging level -> Extended*.
2. Reproduce the problem, then remember the exact time it happened.
3. Collect logs:
*Settings -> General -> Advanced -> Export logs and system info*.
4. Send the file to [qa@adguard.com](mailto:qa@adguard.com):
	- include `[iOS]` keyword and `396` issue number in the subject of your email
	- specify the exact time when the issue occurred

**Comment by emeritaacuity0u** [comment]
@maxikuzmin complete.

**Comment by emeritaacuity0u** [comment]
@maxikuzmin - I have worked out some additional details that allow it to connect on my network. What I need from you is to tell me whether there is a security or privacy issue with the setting I have changed.

Additionally to the original report, I could not ping the IPv6 IP that the AdGuard VPN app wanted to connect to from iOS or macOS when connected to my home network. When switching to a mobile data connection, it worked fine, indicating an issue somewhere between my home network and my ISP.

Performing a `traceroute6` showed that it could not get past my router, which led me to dive deeper into my router's settings.

By default, the FRITZ!Box 7590 AX supports a native IPv6 connection, and up until now, I have not had any issues with IPv6 across many models in the FRITZ!Box range. This suggests that maybe AdGuard VPN handles IPv6 differently in some way.

After searching through a range of settings related to IPv6, disabling/enabling options and testing as I went, I finally came across a setting called **"Allow IPv6 prefixes announced by other IPv6 routers in the home network"** under **Network > IPv6 > Additional Settings** in the FRITZ!Box 7590 AX dashboard. Enabling this allowed AdGuard VPN to connect using IPv6 as a preferred IP version.

Given the above information, can you tell me whether:
1. There is a concern for me having this enabled, relating to privacy or security, and
2. Whether there is something that AdGuard VPN would need to change in the future to prevent other FRITZ!Box users from encountering similar issues with AdGuard VPN?

Resources
https://en.avm.de/service/knowledge-base/dok/FRITZ-Box-7590-AX/1239_Setting-up-an-IPv6-subnet-in-the-FRITZ-Box/
<img width="751" alt="Screenshot 2024-10-26 at 3 37 02 pm" src="https://github.com/user-attachments/assets/ed14170a-7090-4ee5-815d-3784a8e1c88c">
[FRITZ!Box 7590 AX > Network > IPv6.pdf](https://github.com/user-attachments/files/17529141/FRITZ.Box.7590.AX.Network.IPv6.pdf)

**Comment by maxikuzmin** [comment]
@emeritaacuity0u I got your email, but it seems you forgot to attach the logs :)

**Comment by emeritaacuity0u** [comment]
I can no longer reproduce the issue, if it occurs again I'll re-open the issue. Thanks for your time.

**Comment by maxikuzmin** [comment]
@emeritaacuity0u glad to hear that, if it happens again, reopen the issue. Good luck!

**Comment by emeritaacuity0u** [comment]
@maxikuzmin please reopen this, the issue has occurred again.

**Comment by maxikuzmin** [comment]
@emeritaacuity0u could you please reproduce the problem and send the logs to our email as instructed?

**Comment by maxikuzmin** [comment]
@emeritaacuity0u any news?
