### ISSUE TITLE
AdGuard VPN mess up AdGuard DNS connection (AdGuard Personal DNS through AdGuard Pro for iOS)

### ISSUE THREAD

**Issue by Krisnapong** [AdguardTeam/AdGuardVPNForiOS#403]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN  version

2.4

### Environment

- OS: iPadOS 17.7.2
- Device: iPad Pro 2nd gen

### Operating mode

VPN

### Exclusions mode

None, AdGuard VPN app works in integrated mode

### Which DNS server do you use?

None, AdGuard VPN app works in integrated mode

### Issue Details

Steps to reproduce:
1. AdGuard Pro for iOS connect to AdGuard Personal DNS (Singapore server)
2. Turned on AdGuard VPN (Singapore server selected)
3. AdGuard Personal DNS automatically pick Netherlands server (which is so far away)

### Expected Behavior

When AdGuard VPN is connecting to Singapore server, AdGuard Personal DNS should connect to Singapore server (instead of Netherlands server). 

### Actual Behavior

When AdGuard VPN is connecting to Singapore server, AdGuard Personal DNS is connected to Netherlands server. It should be selecting Singapore server since VPN is connect to Singapore isn’t it?

### Screenshots

<details><summary>Screenshot 1</summary>

![image](https://github.com/user-attachments/assets/d0f1e409-6d36-432b-ab3f-77d736189417)

![image](https://github.com/user-attachments/assets/460df352-a0c3-4cb2-8d95-d561a32838ef)

</details>

**Comment by Krisnapong** [comment]
Seems to be okay now. Both VPN and DNS connect to servers in the same country. 

![IMG_0137](https://github.com/user-attachments/assets/c21f7b73-b5cb-40ab-bad3-4be6d114bb90)

**Comment by Versty** [comment]
@Krisnapong Hi! 

We are happy to hear that DNS server selection is now working correctly. 
Please let me know and reopen this issue if the problem reappears in the next few days.
