### ISSUE TITLE
AdGuardVPN is not working on iPhone?

### ISSUE THREAD

**Issue by Macajp** [AdguardTeam/AdGuardVPNForiOS#405]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Ask a question

I installed AdguardVPN on my iPhone but it is not working properly. The reason is that when you activate the VPN and launch Chrome or Safari on your iPhone and search for the IP address from there, the name of your provider and Ip address is displayed (I have a contract with). When you activate the VPN on the PC version, the IP becomes the specified country and you can confirm that the VPN is enabled.

Why? 

And what should I do?

**Comment by Macajp** [comment]
The problem was solved.
The cause was that the VPN protocol was set to HTTP/2 by default. By changing it to QUIC, the VPN became effective, and as a result, my real IP and provider name no longer appeared even when I searched for my IP address.

Sorry and Thank you.

**Comment by Versty** [comment]
@Macajp We are glad to hear that you have found the solution that works for you.
