### ISSUE TITLE
Problem with finding location

### ISSUE THREAD

**Issue by seeemyon** [AdguardTeam/AdGuardVPNForiOS#409]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN  version

2.4, 2.5 beta 1

### Environment

- OS: 18.2
- Device: iPhone 13

### Operating mode

VPN

### Exclusions mode

Regular

### Which DNS server do you use?

Default

### Custom DNS

checked all of DNS server. 

### Issue Details

Steps to reproduce:
1. Install app (4 times)
2. Logged. Usually try several times because it is can not connect to server and write: try one more time.
3. Try to find location. On this step huge problem. Have no idea, but it can be success just 2 times from 10. Usually it is can't find location.

### Expected Behavior

Alway has problem with finding location. Usually it is can't find with different internet and servers and types. Tried change dns server and protocols. Same problem with all. With T-mobile carrier and Nevalink (home Internet) same problems. With Beline much eysier to find location. 

### Actual Behavior

Wrote to support 03.12.2024 mail information about bugs with numbers #991731 and 31001144. Still wait for solution but wrote to give money back because  service is bad. Any way sent you log files here. Maybe it can help you.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

### Additional Information

[adguard_vpn_logs_2.5.0_26902__2212_150459.zip](https://github.com/user-attachments/files/18221806/adguard_vpn_logs_2.5.0_26902__2212_150459.zip)
![IMG_5375](https://github.com/user-attachments/assets/6756b817-d0b1-4c78-9aac-cab58fb509cd)
![IMG_5376](https://github.com/user-attachments/assets/f4c35b67-4669-44a9-9b62-b8f36cf2a3b8)
![IMG_5377](https://github.com/user-attachments/assets/7294f96d-13e1-4cc9-b485-08eb19204ec6)

**Comment by Versty** [comment]
@seeemyon Hi! 
In this case, we recommend switching to the more stable HTTP/2 protocol. 

Most likely access is restricted by the ISP, so it's not an application bug. The best solution at this moment is to close the app completely, wait 30 minutes, and then launch it again.
