### ISSUE TITLE
Downloads from Apple TV App do not work

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/AdGuardVPNForiOS#41]
I can't download movies from my library with the Apple TV app while being connected to AdGuard VPN.

Steps to recreate:
- connect to AdGuard VPN (Germany, Frankfurt in my case)
- open Apple TV App on your iPhone
- try to download a movie from your library or Apple TV+
- the Download fails

If works fine with AdGuard VPN disabled.

AdGuard VPN 1.0.2
iOS 14.2.1

**Comment by zzebrum** [comment]
@iDjay with any server? Can you watch a movie with VPN enabled?

**Comment by iDjay** [comment]
Seems to be working now, not sure why it didn't work last time.
