### ISSUE TITLE
No connectivity after switching between WiFi and LTE

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardVPNForiOS#45]
Similar to my AdGuard DNS issue, my connectivity crashes when iOS switches between WiFi and LTE automatically. It takes around 30 seconds until it reconnects.

- iOS 14.3
- AdGuard VPN 1.0.3 
- Standard Mode + AdGuard DNS 
enabled via AdGuard VPN.
- No additional VPN profile installed

The logs were collected when I had no connectivity.

https://we.tl/t-4bDbbq1cV5

**Comment by ameshkov** [comment]
Just in case, could it be that once of these networks are IPv6-only enabled?

**Comment by iDjay** [comment]
Actually not sure. My router is a FritzBox 6591 Cable which I got from my internet provider.
It means that the settings are limited and I can't configure IPv6 manually. Is there any other way to check it?

**Comment by ameshkov** [comment]
Well, that's a good question:) Wait a litle bit, it should be clear from your logs

**Comment by iDjay** [comment]
I disabled "Wi-Fi assist" as a temporary solution.

**Comment by ameshkov** [comment]
There'll be an update next week that'll resolve this issue.

**Comment by iDjay** [comment]
Thanks! My temporary solution works so far 😊

**Comment by iDjay** [comment]
Quick Update: it‘s more stable with the current version but it‘s still pretty unstable while having slow connection speed.
