### ISSUE TITLE
Shortcuts support

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardVPNForiOS#47]
I would really like to use automations with AdGuard VPN.
F.e. "Turn off VPN connection when opening Disney+."
Therefore you need to implement shortcuts to Apples shortcuts app.
![image](https://user-images.githubusercontent.com/4127356/104776860-06b43780-577b-11eb-81f3-6e64f315bbc1.png)

**Comment by denis9229** [comment]
Hello, thanks!
We opened the task and will take it to work in the near future.
