### ISSUE TITLE
Buffering YouTube app

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/AdGuardVPNForiOS#48]
I'm experiencing a lot of buffering while being connected to AdGuard VPN and watching 1080p videos on YouTube. Watching 2160p videos doesn't work at all.
My download speed is ~300mbps according to speedtest.net while being connected. What's causing the problem? It works fine when I disable AdGuard VPN.

iPhone 12 Pro iOS 14.3
AdGuard 1.03 (Germany - Frankfurt,40ms, AdGuard VPN DNS enabled)
YouTube 15.49.4 (latest version)

**Comment by zzebrum** [comment]
@iDjay is Adguard VPN running in integration mode with AdGuard adblocker?

**Comment by iDjay** [comment]
No, I just have safari ad blocking enabled not Adguard DNS via "Adguard".

**Comment by iDjay** [comment]
Settings:
![image](https://user-images.githubusercontent.com/4127356/105011139-ddc2c980-5a3c-11eb-85cd-1fe88ff4a1ee.png)
![image](https://user-images.githubusercontent.com/4127356/105011151-e1565080-5a3c-11eb-90b8-3a96fa7ebc80.png)
![image](https://user-images.githubusercontent.com/4127356/105011157-e4514100-5a3c-11eb-81c9-7f0b330b30c4.png)

**Comment by iDjay** [comment]
Do you need logs?

**Comment by zzebrum** [comment]
@iDjay honestly, I'm not sure if logs can help :( but it's better to have logs: apple@adguard.com
Does it happen with any location?

> My download speed is ~300mbps according to speedtest.net while being connected.
the download speed is very impressive!

**Comment by iDjay** [comment]
@zzebrum logs sent! I did not test other locations yet.

**Comment by iDjay** [comment]
No improvement with 1.0.5

**Comment by iDjay** [comment]
Seems to be enhanced and fixed.

**Comment by iDjay** [comment]
Need to re-open it, the issue is back. 4K doesn‘t work at all.

**Comment by ameshkov** [comment]
Any server? What speed does the speedtest app show?

They now have a special "video" test in the app, might make sense to check it as well.

**Comment by ameshkov** [comment]
Well, there's a "Video" tab in the Speedtest iOS app

**Comment by iDjay** [comment]
True, I never used the app, just the website. I'll test it as soon as the problem occurs, at the moment it's working as intended.
