### ISSUE TITLE
Ability to use custom DNS server (DoT or DoH) other than the few presets

### ISSUE THREAD

**Issue by stramargio** [AdguardTeam/AdGuardVPNForiOS#55]
### Problem Description

It's not possible to use a custom DNS service (think of NextDNS for ex.) other than Cloudflare, Quad9 and few others.

### Proposed Solution

Add the ability to set a custom DNS (DoT or DoH) endpoint.

### Alternatives Considered

Using AdGuard App and set a custom DNS.
But this isn't an alternative.

**Comment by ameshkov** [comment]
We will definitely implement this.

However, note that you can use AG app alongside AG VPN. You just need to use "Integrated" mode in AG VPN.

**Comment by stramargio** [comment]
Thanks for the quick reply!

Yep, I know that with AG app it is possible. But - you know - I would like to be able to use a custom dns without installing and using another application.

Thanks again and good luck!

**Comment by iDjay** [comment]
And please an option to select the DNS server (if that‘s possible).
![1E7BFC7D-474F-4279-BD17-0C726C7EA25D](https://user-images.githubusercontent.com/4127356/109485191-ab67ab80-7a81-11eb-9de6-503fb48b39c3.png)

**Comment by stramargio** [comment]
Hi guys, this is just a follow up. Is there anything new here?
Thanks again for your work.

**Comment by stramargio** [comment]
up.

**Comment by ameshkov** [comment]
This feature is planned for January

**Comment by mnvr1991** [comment]
I’d like to have this as well! 
I’m using the personal Adguard DNS server fire some time and really like it. But don’t want to use the integrated mode as this is a bit slower than general mode (own vpn protocol).

So please do implement this!

**Comment by ameshkov** [comment]
Sorry that it takes so long, we'll definitely implement this one soon.
