### ISSUE TITLE
Network settings

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardVPNForiOS#56]
Is it possible to add network settings similar to your „AdGuard“ app?
![426CCD05-8D08-444A-AF5B-9EBA51146F44](https://user-images.githubusercontent.com/4127356/108352564-52795700-71e7-11eb-916e-e9967097f0ed.png)

**Comment by denis9229** [comment]
Yes, I think we will do it!
But now it isn't a priority feature.
