### ISSUE TITLE
Apps which detect VPN connection

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardVPNForiOS#57]
Decided to give you an overview about apps which do not work with AdGuard VPN instead of creating single issue threads:
Apple Music: sometimes playing music does not work
Apple TV: downloading Movies / tv shows fails sometimes
DAZN: thinks I‘m not in Germany (although I am), App doesn’t load
Disney+: doesn‘t load content
Prime Video: app works, but detects VPN -> can‘t play videos
REWE (my local supermarket app lol): can‘t access their content.
Sky Go (similar to Dazn/ Netlix): playing videos doesn’t work -> technical issue
waipu.tv (TV livestream): thinks I‘m not in Germany -> doesn‘t work.

iPhone 12 Pro, iOS 14.4, AdGuard VPN 1.0.6
Connected to Germany Frankfurt / Berlin.

will update the thread over time.

**Comment by denis9229** [comment]
Hello!
We don't work with streaming yet
But it's a work in progress and hopefully, this feature will be available at the end of this quarter.

**Comment by iDjay** [comment]
Update:
„Mydealz“ doesn’t work anymore with AdGuard VPN. 

Is a „only works with selected apps“ feature ,similar to the one with websites, possible?

**Comment by iDjay** [comment]
huh? For some reason my old account got deleted...
anyway, the issue still exists, I tried to exclude disneyplus.com for example but it doesn't affect the app I guess?

**Comment by ameshkov** [comment]
> anyway, the issue still exists, I tried to exclude disneyplus.com for example but it doesn't affect the app I guess?

It actually should affect. However, I think Disney Plus uses more domains:
https://www.netify.ai/resources/applications/disney-plus

You'll also need to add pairs: `*.disneyplus.com` AND `disneyplus.com` to cover all domains including subdomains.

**Comment by iDjay** [comment]
Nope, doesn't work.

**Comment by ameshkov** [comment]
Have you added ALL domains that Disney Plus uses or just these two records?

**Comment by iDjay** [comment]
![image](https://user-images.githubusercontent.com/83946731/117643221-731ed080-b188-11eb-873f-e24d740e5e05.png)

**Comment by ameshkov** [comment]
You need `*.domain` records for all domains, not just a single one

**Comment by iDjay** [comment]
![image](https://user-images.githubusercontent.com/83946731/117646526-29d08000-b18c-11eb-8625-86584e513caa.png)

Like this? Still not working... :(

**Comment by iDjay** [comment]
Also tried it with other apps which do not work with AdGuard VPN, but no success.
