### ISSUE TITLE
Please add zh-TW locale in app.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdGuardVPNForiOS#6]
Chinese Traditional (zh-TW) for Taiwan.

**Comment by lancelot-moon** [comment]
Many added locales aren't 100% translated in the app, ex: Japanese, Korean, Croatian...etc.
Some added locales' approved translations are even lower than zh-TW.
Why did Lena ask me to translate zh-TW to the end first, and then she will add zh-TW into the app?

**Comment by ameshkov** [comment]
@lancelot-moon hm, strange.

@IvanIin why is this even marked resolved? I can see in the code that Traditional Chinese is missing
