### ISSUE TITLE
Change Wi-Fi Protection functionality

### ISSUE THREAD

**Issue by eduardoaddad** [AdguardTeam/AdGuardVPNForiOS#60]
Change functionality when you are on a trusted network to when you are as trusted and do not remove the network as trusted

In trusted networks if you want to connect manually you need to remove the network as trusted but when you want to connect you don't need to remove as trusted

**Comment by zzebrum** [comment]
@eduardoaddad I didn't get what is the problem :( Can you explain in more detail, please?

**Comment by eduardoaddad** [comment]
> @eduardoaddad I didn't get what is the problem :( Can you explain in more detail, please? 

When manually connecting to a trusted network, keep it as a trusted network instead of removing it from the trusted network.

Changing this improves this feature because the user will be able to connect to a trusted network and not need to add the network as trusted all the time

**Comment by Aydinv13** [comment]
@eduardoaddad How will it improve auto-protection feature? When we connect to a trusted network using auto-protection enabled the network stops being trusted so it's deleted automatically.

**Comment by eduardoaddad** [comment]
When connecting to a trusted network removes the trusted network and makes it connected automatically and will need to repeat the process again in order to add the trusted network again

Could allow trusted networks to connect manually without having to remove the network as trusted

**Comment by zzebrum** [comment]
@eduardoaddad what is the point of a trusted network in this case?

**Comment by Aydinv13** [comment]
@eduardoaddad unfortunately, we don't find it necessary to change wi-fi protection functionality because it will be kind of confusing. Thank you for your request! I've closed the issue. Feel free reopening it anytime
