### ISSUE TITLE
AdGuard VPN is set to integration mode but still shows "Standardmodus"

### ISSUE THREAD

**Issue by sergerosenthaler** [AdguardTeam/AdGuardVPNForiOS#67]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard VPN version:**
  - 1.0.8 (231)
- **VPN mode:**
  - 
- **Device:**
  - iPhone 12 Pro Max and iPad Pro 11-inch (2nd generation)
- **Operating system and version:**
  - iOS and iPadOS 14.4.1

### Expected Behavior

In integration mode on AdGuard VPN screen it should reflect "integration mode"

### Actual Behavior

AdGuard VPN is set to integration mode but still shows "Standardmodus"

### Screenshots

<details><summary>Screenshot:</summary>

![IMG_0071](https://user-images.githubusercontent.com/25068100/111444495-b4f04500-870a-11eb-9d2a-e2d61cdfff94.PNG)
![IMG_1889](https://user-images.githubusercontent.com/25068100/111444501-b6ba0880-870a-11eb-8c63-2380e2177dcc.PNG)

</details>

**Comment by zzebrum** [comment]
Status mode on the main screen corresponds to Exclusions mode (Regular and Selective) and not to General and Integrated. It's confusing though :(

**Comment by sergerosenthaler** [comment]
@zzebrum Check my comment in another issue https://github.com/AdguardTeam/AdGuardVPNForiOS/issues/68#issuecomment-800996702

**Comment by zzebrum** [comment]
@sergerosenthaler I guess we shouldn't show status regular-selective mode on the main screen when the app is working in integration mode.

**Comment by zzebrum** [comment]
#70
