### ISSUE TITLE
Mix between "Standardmodus" und "Allgemeiner Modus" in German version

### ISSUE THREAD

**Issue by sergerosenthaler** [AdguardTeam/AdGuardVPNForiOS#68]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard VPN version:**
  - 1.0.8 (231)
- **VPN mode:**
  - 
- **Device:**
  - iPhone 12 Pro Max and iPad Pro 11-inch (2nd generation)
- **Operating system and version:**
  - iOS and iPadOS 14.4.1

### Expected Behavior

Everywhere in the app either "Standardmodus" or "Allgemeiner Modus" should be used, not mixed. At themoment it's very confusing.

### Actual Behavior

On start screen (menu bar 1) and on Exceptions (menu bar 2) "Standardmodus" is used. In the settings unter "Ausführungsmodus" and "DNS-Server" "Allgemeiner Modus" is used.

### Screenshots

<details><summary>Screenshot:</summary>

![IMG_1889](https://user-images.githubusercontent.com/25068100/111445793-0816c780-870c-11eb-8696-d3f94acf7b09.jpeg)
![IMG_1892](https://user-images.githubusercontent.com/25068100/111445854-15cc4d00-870c-11eb-82e3-f8bd521d7041.jpeg)
![IMG_1890](https://user-images.githubusercontent.com/25068100/111445867-195fd400-870c-11eb-9cf5-b5d6c52095d7.jpeg)
![IMG_1891](https://user-images.githubusercontent.com/25068100/111445873-1c5ac480-870c-11eb-975b-74345470e17b.jpeg)

</details>

**Comment by el-termikael** [comment]
@sergerosenthaler Hello,

I agree that this looks a bit confusing. Yet, these are two different modes.

Regular mode ("Standardmodus" in German) is the opposite of Selective mode – both can be found in the Exclusions tab. General mode ("Allgemeiner Modus") is an operating mode, opposed to Integrated mode (App settings –> Operating mode). These ones use AdGuard VPN and IPSec protocols correspondingly.

Therefore, despite the apparent synonymy, these mode names should not be mixed.

**Comment by sergerosenthaler** [comment]
@el-termikael Got it, "regular" and "selective" are also available for the browser plug ins, "general" and "integrated" only on iOS/iPadOS to work along AdGuard:-) But then at least that on the attached screenshot must be changed from "Standardmodus" to "Allgemeinen Modus". As exclusions are not available while in "integrated mode", not "regular mode". Got it?
![IMG_1893](https://user-images.githubusercontent.com/25068100/111457033-f89d7b80-8717-11eb-82a0-04c0be83c526.jpeg)

To solve this confusion may be adding a second line with a description on the start page would make it more understandable?

Something like
EN:
Regular mode
"Integrated mode" is active to work in along with AdGuard. Some features like "selective mode" are not available.

DE
Standardmodus
Der "Integrierte Modus" ist aktiv, damit AdGuard VPN zusammen mit AdGuard funktioniert. Einige Funktionen wie der "Selektive Modus" stehen nicht zur Verfügung.

**Comment by sergerosenthaler** [comment]
@el-termikael And by the way, while playing around with the app, I noticed the following: If you switch from "regular mode" to "selective mode" (this has nothing to do with "general and integrated mode":-)) the description on the start screen is not updating. It updates only after an app restart or when you connect/disconnect the VPN.

**Comment by zzebrum** [comment]
@sergerosenthaler you are right, I've created bug report #69

**Comment by sergerosenthaler** [comment]
@zzebrum No, this is not fixed, in fact this is a third bug. "Integrated mode is active, on the "selective mode" screen (2nd tab in menu bar), you see the message displayed:...not available in "integrated mode" you have to switch to "general mode" in the settings. But in fact you have to switch to the "regular mode".

**Comment by el-termikael** [comment]
@sergerosenthaler I checked, there is a correct translation on Crowdin (with 'Allgemeinen Modus'): https://crowdin.com/translate/adguard-applications/18204/en-de#3936026
I guess we need to pull German translations
