### ISSUE TITLE
Regular\selective status is not changed on the main screen until restarting the tunnel

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdGuardVPNForiOS#69]
### Issue Details

- **AdGuard VPN version:**
  - 1.0.8(231)
1. Connect to any location
2. Switch to Selective mode
3. Go to main screen
### Expected Behavior

status: Selective mode

### Actual Behavior

status: Regular mode

**Comment by Aydinv13** [comment]
Fixed
