### ISSUE TITLE
Integration mode

### ISSUE THREAD

**Issue by jonsnowlb** [AdguardTeam/AdGuardVPNForiOS#7]
How should I set up my AdGuard pro app to work properly with AdGuard VPN? I’m on iOS 14. Thank you.

**Comment by iDjay** [comment]
AdGuard VPN = Integrated mode
AdGuard DNS = split Tunnel

It's indeed a bit unclear at the moment.

**Comment by ameshkov** [comment]
Well, AdGuard VPN enables integrated mode automatically so in theory there should be no additional setup :)

**Comment by jonsnowlb** [comment]
Thank you so much
