### ISSUE TITLE
AdGuard and AdGuard VPN are used together with very high ping

### ISSUE THREAD

**Issue by Richelieu4771** [AdguardTeam/AdGuardVPNForiOS#75]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard VPN version:**
    1.0.8(231)
  - 
- **VPN mode:**
    IPSec
  - 
- **Device:**
    iPhone 12 pro max
  - 
- **Operating system and version:**
    iOS 14.4.2
  - 

### Expected Behavior
As it uses a geographically close Korean server, the ping should be low.

### Actual Behavior
No matter which server I choose, the ping is very high.

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/68171816/113907235-12f6e080-9810-11eb-8b26-4c774cc2f40d.png)

There is a screenshot of a list of more than 100ms for all servers, even South Korea.

![image](https://user-images.githubusercontent.com/68171816/113904036-957da100-980c-11eb-9e33-a08453d660f2.jpeg)

The screenshot above shows the connection information of the iPhone currently in use.

"현재 엔드포인트 정보:
Status: Connected
ID: a3Jfc2VvdWw=
Country: South Korea
City: Seoul
Premium only: Yes
Ping: 40 ms
Ping bonus: 0 ms
Domain name: m9009-kr-icn-01-l3mt8vhy.adguard.io
Connected IPv4: 79.110.55.50:443
Connected IPv6: Unknown"

The above citation is the connection information for the iPod Touch 6th generation, which is used through the same IPSec protocol and AG&VPN App version but operates on iOS 12.5.2.
Ping is just 40ms.

</details>

### Additional Information

The difference between two informations seems to be the difference between IPv4 and IPv6. Using IPv6 AAAA blocking in the AdGuard app does not solve the problem, so it is difficult for me to solve it alone.

**Comment by artemiv4nov** [comment]
Well, this behavior exists because of technical features. All AdGuard VPN traffic routes to VPN, and data could be incorrect. For this moment, we can't fix this asap but we will research a few ways in the future
