### ISSUE TITLE
WiFi exclusions aren't displayed on iOS 15

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/AdGuardVPNForiOS#87]
The option to exclude my own Wi-Fi network is not available anymore since the update to 1.0.15. Bug or Feature?
![IMG_0587](https://user-images.githubusercontent.com/83946731/124361725-db41de00-dc30-11eb-9251-6571fbc060a6.PNG)

**Comment by iDjay** [comment]
Not available with 1.0.16 too.

**Comment by Aydinv13** [comment]
Wi-Fi auto-protection is supposed to be used with Wi-Fi network, not with mobile network. What if you change to Wi-Fi?

**Comment by iDjay** [comment]
@Aydinv13 no difference. Keep in mind that I‘m on the iOS 15 beta (19A5281j). Maybe a compatibility issue?

**Comment by Aydinv13** [comment]
@iDjay It's reproducible on iOS 15 so it's probably compatibility issue. Thanks for the report! We'll work on it

**Comment by iDjay** [comment]
There is also the bug that it no longer disconnects automatically.

**Comment by iDjay** [comment]
Could you figure out what causes the issue?

**Comment by artemiv4nov** [comment]
Well, we have a situation with this feature because it doesn't work on iOS 15. At first sight, the feature requires permissions by Apple.
We will investigate other ways to make this feature work on iOS 15 in the future.

**Comment by artemiv4nov** [comment]
We removed this functionality in the new 2.1 version, so the task can be closed
