### ISSUE TITLE
Xiaomi Home app is not working with VPN

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdGuardVPNForiOS#89]
Xiaomi Home cameras are not initializing in the application. Disabling VPN solves the problem. I tiried on PL and USA VPN connection. I am using mainline china Xiaomi Home application

ticket id: 512743

**Comment by ameshkov** [comment]
@zzebrum quick question - does it work with IPSec?

**Comment by zzebrum** [comment]
@ameshkov yep, it works with IPSec, I posted more information and logs in Jira issue. 
But I haven't checked the problem with android yet.
